"""The CLOSED KEYSPACE — what IS a key, and the one validator that answers it.

Spec §0: *"The keyspace is CLOSED — an undeclared key is NOT a key.
Every legal key is either enumerated in this spec or generated by one of its
declared PARAMETRIC families … Anything outside it is REJECTED: reading,
setting, or resolving an undeclared key is an ERROR that NAMES the offending
key."* This module is the code-side DECLARATION of that set and the single
predicate over it, :func:`key_validity`.

What this module answers, and what it does NOT
----------------------------------------------
This module answers **"is this a key at all?"**
``config_keys._KEY_ROUTES`` / ``KNOWN_CONFIG_KEYS`` answer a DIFFERENT
question — **"where does a ``config set`` of this key land, and is it reachable
from the CLI?"**. The two lists are therefore NOT duplicates and must not be
collapsed: the settable surface is a SUBSET of the keyspace (``run_args`` and
``transform_settings`` are real keys with no CLI route; ``meta.*`` keys are real
keys that are never settable at all). :func:`~kanibako.settings.settings_keyspace`'s set
is the superset, and ``tests/test_settings_keyspace.py`` asserts that direction
so the two cannot silently diverge.

⚑ WHAT IS DECLARED HERE IS THE **SPEC's** KEY SET, NOT THE CODE's
------------------------------------------------------------------
A key the spec declares is valid here even when no consumer reads it yet
(``system.agent`` until P7 wires agent selection; ``agent.<a>.canon`` until the
canon-books phase). §0's closed keyspace is about DECLARATION; an unread key is
not an undeclared one. The alternative — gating each key on its implementing
phase — makes this module a moving target and reintroduces exactly the "which
list is authoritative" question §0 exists to settle.

Coverage boundary — AUTHORITATIVE vs SUPPORTING (read before relying on this)
-----------------------------------------------------------------------------
* **AUTHORITATIVE (complete, test-pinned):** the ``pref.*`` allowlist surface —
  ``system.agent`` and every ``agent.<agent>.**`` form (§2h). ``settings_prefs``
  filter 1 depends on this being exact, and it is.
* **SUPPORTING (best-effort):** every other scope. These entries exist so an
  error MESSAGE can be accurate ("``box.image`` is a real key, it is just not
  requestable") rather than misleading. A gap here can only degrade a message,
  never an outcome: under §2h any target outside the allowlist is refused by the
  allowlist filter regardless of what this module says about it.

That boundary is why the LAUNCH path was the last consumer wired, and it now is:
``settings_launch._refuse_undeclared_snapshot`` reads this module and RAISES,
so an undeclared key stored anywhere in the cascade is a user-visible failure
rather than a value nothing reads. It was taken as a deliberate act on a
measurement — the REPORT-ONLY ``settings_keyspace_probe`` ran armed over the whole
unit suite first — after :data:`RETIRING_KEYS` reached empty. ⚑ The real-store
sweep that gate also named (migration-issues M-1/M-2) was WAIVED rather than run,
so the residual risk sits exactly there and nowhere else.

THREE ANSWERS, NOT TWO
----------------------
A dotted path fails to be a key for two OPPOSITE reasons: it names a declared
INTERIOR of the keyspace (``meta``, ``box``, ``agent.claude``, ``meta.box.auth``),
or it names nothing at all. :func:`key_class` returns which — see
:class:`KeyClass`. :func:`key_validity` is the key-or-not VIEW of it, and is what
every SET boundary wants, since at a write site both are equally not-a-key.

The second question: what is this path INTO A STORE?
----------------------------------------------------
:func:`key_class` judges a dotted STRING. A resolved store also holds VALUE
addresses, scaffolding nodes and plain data, none of which are keys and none of
which are defects. :func:`classify_store_path` (with :func:`container_notes` and
:func:`walk_store_paths`) answers that second question, and it is ONE carrier
with THREE consumers — the pytest write census, the resolve probe, and the
launch-seam REFUSAL, which is the only one of the three that raises.

PURE. No I/O, no plugin import at module load. Everything the module cannot know
about this machine is an injected parameter, so it stays pure and testable: the
valid AGENT names (``valid_agents``, whose one production supplier is
``settings_prefs.default_valid_agents``), the plugin-declared agent leaves
(``agent_leaves``), and which agents those leaves COVER
(``agents_with_known_leaves`` — see :func:`key_class`).

⚑ THAT PURITY MAKES THE INJECTED SETS EXPENSIVE, WHICH IS WHY THEY ARE ASKED LAST.
Two of the three are answered in production by ``settings_keyspace_probe``, which
IMPORTS every installed plugin to answer them — so ASKING one is I/O even though
this module does none. :func:`key_class` therefore judges as much as it can from
its own declarations before it puts a question to either, and both arrive as things
to ASK rather than as materialised sets (:class:`_EffectiveLeaves`,
:func:`_agent_tail_reason`'s ``leaves_known``). It changes no verdict; it decides
whether every ``box.image`` resolve pays for a plugin import.
"""

from __future__ import annotations

import enum
import re
from typing import (
    Any,
    Callable,
    Collection,
    Container,
    Final,
    Iterator,
    Mapping,
    NamedTuple,
    Sequence,
)

from kanibako.settings.kb_store import BINDING_DERIVATIONS_NODE, SCOPE_CONTAINMENT
from kanibako.settings.keystore import KeyStore
# ⚑ MODULE SCOPE, and it closes no cycle: ``settings_categories`` is pure — it
# imports stdlib only, with ``kb_store`` and ``keystore`` behind ``TYPE_CHECKING``.
from kanibako.settings.settings_categories import CATEGORY_FAMILY_ROOTS

# ---------------------------------------------------------------------------
# The keyspace version stamp
# ---------------------------------------------------------------------------

#: The declared keyspace VERSION — one leg of the three-way stamp (the spec
#: header · the manifest's ``registry.keyspace`` field · this constant),
#: flipped to ``"1.8.0"`` in-tree before the prod promote per
#: Part-4-as-amended. Imported by nothing yet — C2's CI stamp assertion is
#: its first consumer.
KEYSPACE_VERSION: Final[str] = "1.8.0rc"

# ---------------------------------------------------------------------------
# Layer 1 — config.* (spec §1)
# ---------------------------------------------------------------------------

#: The Layer-1 bootstrap CONFIG keys (spec §1). Human-edited in
#: ``kanibako_config.yaml``; never CLI-settable (block B2) but unquestionably KEYS.
DECLARED_CONFIG_LEAVES: Final[frozenset[str]] = frozenset({
    "data", "settings", "agents", "primary_workset", "registry", "journal",
})

# ---------------------------------------------------------------------------
# Layer 2 — the scope SCALAR leaves (spec §2b / §2c / §2e / §2g)
# ---------------------------------------------------------------------------

#: ``system.<leaf>`` (spec §2g). ⚑ ``system.agent`` is the SPEC name
#: (D-M2 superseded 2026-07-29) and, since P7, the ONLY spelling: the stored
#: ``system.default_agent`` is RETIRED and REFUSED by name at assembly
#: (``settings_assemble.RETIRED_FILE_KEYS``).
DECLARED_SYSTEM_LEAVES: Final[frozenset[str]] = frozenset({
    "channelroot", "template", "canon", "backup", "cache", "runtime",
    "agent", "setup_completed",
})

#: ``system.channels.<leaf>`` (spec §2g).
DECLARED_SYSTEM_CHANNEL_LEAVES: Final[frozenset[str]] = frozenset({
    "common", "chat", "broadcast", "mailboxes", "share",
})

#: ``system.auth.<leaf>`` — the auth 3-tier gate (spec §2g/§2c; settable ONLY
#: from the system floor per §0).
DECLARED_SYSTEM_AUTH_LEAVES: Final[frozenset[str]] = frozenset({"share_allowed"})

#: ``box.<leaf>`` (spec §2b). ⚑ ``box.agent_name`` is RETIRED (§2b
#: ) and is deliberately ABSENT — its replacement is ``pref.system.agent``.
DECLARED_BOX_LEAVES: Final[frozenset[str]] = frozenset({
    "image", "share_images", "images_store", "canon", "shell", "enable_vault",
})

#: ``box.auth.<leaf>`` (spec §2b).
DECLARED_BOX_AUTH_LEAVES: Final[frozenset[str]] = frozenset({
    "global_enabled", "workset_enabled",
})

#: ``workset.<leaf>`` (spec §2c ALL WORKSETS, ALL PROJECTS,
#: STANDALONE, §2e).
DECLARED_WORKSET_LEAVES: Final[frozenset[str]] = frozenset({
    "workspaces", "boxes", "logs", "registry", "template", "canon",
    "kuid", "skip_kuid_check", "vault_ro", "vault_rw", "channelroot",
})

#: ``workset.auth.<leaf>`` (spec §2c).
DECLARED_WORKSET_AUTH_LEAVES: Final[frozenset[str]] = frozenset({
    "share_allowed", "global_sync", "path",
})

#: ``workset.channels.<leaf>`` (spec §2c). TWO sub-families make up the set:
#: the workset-LOCAL type roots (``common``/``chat``/``broadcast``/``share`` —
#: primary+named only, rooted at ``@workset.channelroot``) and the ALL-PROJECTS
#: per-workset ADDRESSES into the SYSTEM stores (``mailboxes``/``share_global``
#: — ``@system.channels.{mailboxes,share}/@meta.workset.name``, present in
#: EVERY mode, keyed ``__PRIMARY__`` | ``<named>`` | ``__STANDALONE__``).
#: Mailboxes still AGGREGATE at system only (§2f) — the workset leaf is the
#: workset's declared ADDRESS into that aggregate, not a second aggregate,
#: which is why the earlier "a workset has no mailboxes" exclusion here was a
#: mis-read (R-35, RATIFIED: fix the CODE): ``meta.box.inbox`` /
#: ``meta.box.share_global`` derive through these keys in the spec's formulas.
#: This set must EQUAL ``settings_launch._WORKSET_CHANNEL_LEAVES`` (the launch
#: floor's allowlist) — a test pins the agreement.
DECLARED_WORKSET_CHANNEL_LEAVES: Final[frozenset[str]] = frozenset({
    "common", "chat", "broadcast", "share", "mailboxes", "share_global",
})

#: ``agent.<agent>.<leaf>`` — the generic per-agent contract (spec §2d).
#: Every one of these ALSO exists as ``agent.default.<leaf>`` (the agent tier's
#: fallback layer, §2).
#:
#: ⚑ This is the AUTHORITATIVE list — ``settings_prefs`` filter 1 rejects on it,
#: so an omission here is a user-visible refusal of a legal request. Each entry
#: carries its §2d line. It is UNIONED with the plugin-declared
#: ``setting_descriptors()`` keys (§0 "Agent specifics are
#: PLUGIN-declared"), which is why ``endpoint`` appearing here is a floor, not a
#: ceiling. ⚑ The union is LAZY and this set is the half asked FIRST — see
#: :class:`_EffectiveLeaves`, which is where the reason lives.
DECLARED_AGENT_LEAVES: Final[frozenset[str]] = frozenset({
    "access",              # §2d (the permission TIER — SUPERSEDES ``auto_approve``)
    "allow_helpers",       # §2d
    "continue_mode",       # §2d
    "bootstrap",           # §2d
    "model",               # §2d
    "run_args",            # §2d
    "transform",           # §2d (WHICH transform; claude declares `tweakcc`)
    "transform_settings",  # §2d
    "endpoint",            # §2d (claude-declared; part of the generic shape)
    "template",            # §2d
    "canon",               # §2d
})

#: The declared agent leaves whose VALUE IS A TABLE — spec §2d calls
#: ``transform_settings`` "agent-scope, sparse, dict-valued".  Its entries are DATA inside
#: the table, never key segments, so NO SCALAR HAS A SLOT AT ONE and every write verb has
#: to refuse it BY NAME rather than store a string where a map belongs.
#:
#: ⚑ IT IS A SUBSET OF :data:`DECLARED_AGENT_LEAVES`, NOT A SECOND KEYSPACE.  These are
#: fully declared, fully READABLE keys; what the split answers is the narrower question
#: "can ``set`` express this value?", which is why the settable surface is derived by
#: SUBTRACTION (:data:`SCALAR_AGENT_LEAVES`) instead of by a second hand-kept list.
#:
#: ⚑ THE COST OF GETTING IT WRONG IS MEASURED: a scalar stored at
#: ``self.transform_settings`` crashed every subsequent ``agent_file.load`` — i.e. every
#: launch, list, info and show — until :func:`kanibako.settings.agent_file.table_value_error`
#: refused it.  That refusal is the FILE-shape half of this same fact, and
#: ``tests/test_settings/test_agent_leaf_shape.py`` pins the two against each other.
TABLE_VALUED_AGENT_LEAVES: Final[frozenset[str]] = frozenset({"transform_settings"})

#: The declared agent leaves whose value is a HOST PATH — the manifest's ``type: path``
#: rows in the ``agent`` scope (``agent.default.{template,canon}`` and the per-node
#: ``agent.<agent>.{template,canon}``).
#:
#: ⚑ IT IS A SUBSET OF :data:`DECLARED_AGENT_LEAVES`, NOT A SECOND KEYSPACE — the same
#: shape as :data:`TABLE_VALUED_AGENT_LEAVES` above and for the same reason: what it
#: answers is a narrower question about a fully declared key, here "does [R147]'s
#: bare-relative refusal reach this value?".  It is the agent-scope half of
#: ``config_keys.is_path_valued_key``; the other scopes' path keys are spelled in full
#: in ``config_keys.KEY_TYPES``.
PATH_VALUED_AGENT_LEAVES: Final[frozenset[str]] = frozenset({"template", "canon"})

#: The declared agent leaves a CLI ``set`` can actually WRITE — every leaf holding a SCALAR.
#: ⚑ DERIVED, NEVER LISTED (P13): a leaf entering :data:`DECLARED_AGENT_LEAVES` becomes
#: settable at both the bare ``agent.default`` spelling and the per-persona one with no edit
#: at either surface.  ``agent.default.{template,canon,run_args,transform}`` were declared
#: ``set: cli+file`` and refused for the whole 1.8.0 cycle precisely because those two
#: surfaces each carried their own hand-kept copy of this set and both fell behind.
SCALAR_AGENT_LEAVES: Final[frozenset[str]] = (
    DECLARED_AGENT_LEAVES - TABLE_VALUED_AGENT_LEAVES
)

# ---------------------------------------------------------------------------
# The ``access`` permission TIER — the one enum-valued agent leaf (spec §2d)
# ---------------------------------------------------------------------------

#: The LEGAL values of ``agent.<agent>.access`` / ``agent.default.access``
#: (spec §2d, R-41), ordered LEAST → MOST permissive:
#:
#: * ``restricted`` — everything prompts.
#: * ``editing`` — the middle tier: free for safe, contained edit-class
#:   operations; ask at the boundaries.
#: * ``full`` — today's bypass (the DEFAULT: the box IS the containment
#:   boundary, so in-box permission prompts are a second fence inside the first).
#:
#: ⚑ The value set is CLOSED (spec §0): an unknown value is REJECTED LOUDLY at
#: BOTH ends — ``config set`` time (``config_keys.access_value_error``) and
#: launch (``targets.assembly.effective_access``). It is NEVER treated as
#: permissive: a typo must not be the difference between prompting and not.
#: Declared HERE, beside the leaf itself, so the settable surface, the launch
#: resolver and the plugin descriptors all read ONE list.
ACCESS_TIERS: Final[tuple[str, ...]] = ("restricted", "editing", "full")


def access_default() -> str:
    """The tier a launch uses when NO scope in the cascade sets ``access``.

    Spec §2d ``:1244`` (``agent.default.access | full``; R-41 CLOSED: option (a),
    today's behaviour preserved).  The value is DECLARED in ``core-defaults.yaml``
    beside the other ``agent.default.*`` behavior floors (D1-2) and read from there.

    ⚑ A FUNCTION, not the retired ``ACCESS_DEFAULT`` constant, and the reason is
    IMPORT DISCIPLINE: this module is imported at MODULE SCOPE by ``config_keys``,
    ``agent_defaults``, ``settings_cli_level`` and ``settings_prefs``, so a
    module-level read would put YAML file I/O on every one of those imports.
    ⚑ FAIL-CLOSED on a declaration outside :data:`ACCESS_TIERS`. Nothing downstream
    re-checks the DEFAULT — ``resolve_access_tier`` validates only a value the
    cascade supplied — so a shipped typo here would silently become the tier every
    unset box runs at, on a permission axis.
    """
    from kanibako.settings.core_defaults import (
        CORE_DEFAULTS_FILENAME,
        behavior_default,
    )

    value = behavior_default("access")
    if value not in ACCESS_TIERS:
        raise RuntimeError(
            f"{CORE_DEFAULTS_FILENAME} declares 'agent_default.access' as {value!r}, "
            f"which is not one of {' | '.join(ACCESS_TIERS)} (spec §2d). Refusing "
            "rather than defaulting every unset box to an unrecognised tier."
        )
    return value

# ---------------------------------------------------------------------------
# The §2a CATEGORIES — parametric over every scope
# ---------------------------------------------------------------------------

#: The bind-shaped categories. ⚑ **ONE SHAPE SINCE 2026-08-08c — all six are
#: DEST-KEYED and TERMINAL.** The category key is the whole of the key and its
#: VALUE is a map keyed by box destination; a destination is DATA, never a key
#: segment, so neither ``<scope>.bindings.<arm>.<name>`` nor
#: ``<scope>.<category>.<name>`` is a key. The ``bindings`` arms got there first
#: (R-5/R-10, 2026-08-06c); ``caches`` / ``seeded`` / ``common`` / ``synced``
#: followed, one segment SHALLOWER — the category token itself ends the key.
#:
#: ⚑ THE OLD "TWO SHAPES" SPLIT IS GONE, and with it the claim that the dotless
#: members are NAME-KEYED with a FREE ``<name>``. The §2h "VALIDITY, not EXISTENCE"
#: clause still holds for parametric families (``env.<VAR>``, ``secret_path.<VAR>``,
#: ``agent.<node>.*``) — it simply no longer has a bind-shaped instance, because a
#: destination inside a terminal map is not a key segment to validate.
#:
#: This set is listed for the record and by VALUE SHAPE; consumers that want the
#: key shape ask :data:`TERMINAL_CATEGORY_TAILS` (⚑ note several still filter the
#: dotted members with ``if "." not in c``, which is a fact about the two-token
#: ``bindings.<arm>`` spelling, not about name-keying).
BIND_CATEGORIES: Final[frozenset[str]] = frozenset({
    "bindings.ro", "bindings.rw", "caches", "seeded", "common", "synced",
})

#: The DEST-KEYED **TERMINAL** category keys (spec §2a), as the segment tail that
#: ENDS a key. A key may end here and nothing may follow: the value is a map whose
#: keys are box DESTINATIONS — data, not keyspace.
#:
#: ⚑ ONE definition. Two predicates read it — :func:`is_terminal_category_tail`
#: (a SUFFIX test, for a caller holding a tail) and :func:`is_terminal_category_key`
#: (a POSITION test, for a caller holding a whole key) — and they must agree on the
#: SET even though they disagree on where it may appear. Consumers: what is a key
#: (:func:`_category_reason`), where a ``pref:`` subtree walk STOPS
#: (``settings_prefs._flatten_pref_node``), and every full-key site that must not
#: mistake a scalar leaf for a category. A walker that descended past a terminal key
#: would manufacture targets this validator then refuses, reporting the wrong fault.
#: ⚑ ALL SEVEN since 2026-08-08c: ``masks`` plus every bind-shaped category.
#: ``caches`` / ``seeded`` / ``common`` / ``synced`` are terminal ONE SEGMENT
#: SHALLOWER than a ``bindings`` arm — the category token itself ends the key.
TERMINAL_CATEGORY_TAILS: Final[frozenset[tuple[str, ...]]] = frozenset({
    ("masks",),
    ("bindings", "ro"),
    ("bindings", "rw"),
    ("caches",),
    ("seeded",),
    ("common",),
    ("synced",),
})


def is_terminal_category_tail(tail: Sequence[str]) -> bool:
    """Does *tail* END at a DEST-KEYED TERMINAL category key? (spec §2a)

    *tail* is a key's segments (a full key or any suffix of one). True for
    ``(…, "masks")``, ``(…, "bindings", "ro"|"rw")`` and each of
    ``(…, "caches"|"seeded"|"common"|"synced")`` — the keys whose VALUE is a
    destination-keyed map. See :data:`TERMINAL_CATEGORY_TAILS`.
    """
    segments = tuple(tail)
    for cat in TERMINAL_CATEGORY_TAILS:
        if len(segments) >= len(cat) and segments[-len(cat):] == cat:
            return True
    return False


def is_terminal_category_key(key: str) -> bool:
    """Is *key* — a WHOLE canonical key — a DEST-KEYED TERMINAL category key? (spec §2a)

    ⚑⚑ NOT :func:`is_terminal_category_tail` HANDED A KEY. That one is a SUFFIX
    test, so it answers True for ``system.channels.common`` — an ordinary path
    SCALAR that merely ENDS in a category token — while its sibling
    ``system.channels.chat`` answers False, routing two members of one family
    differently. This one requires the tail to begin exactly where the SCOPE ends,
    which is the position spec §2a puts a category in: *"the discriminator is the
    ``channels.`` segment, which the channel form always carries and the category
    form never does, so no KEY is ambiguous."* The two take different TYPES —
    segments for the tail, a dotted string for the key — so which question a call
    site asks is visible at the call.

    ⚑ BOTH AXES ARE DERIVED, NEVER ENUMERATED HERE: which tails from
    :data:`TERMINAL_CATEGORY_TAILS`; where a scope may END from
    :data:`~kanibako.settings.kb_store.SCOPE_CONTAINMENT`. A scope is ONE
    segment except the DISCRIMINATED agent tier ``agent.<node>`` (spec §0/§2d),
    which is two — and two is the CEILING, because ``.`` is the key-path separator
    and ``agent_ref.parse_agent_ref`` REFUSES a dotted node. ``pref.*`` is False by
    construction: ``pref`` is not a scope.
    """
    parts = key.split(".")
    for cat in TERMINAL_CATEGORY_TAILS:
        if len(parts) <= len(cat) or tuple(parts[-len(cat):]) != cat:
            continue
        scope = parts[: -len(cat)]
        if scope[0] not in SCOPE_CONTAINMENT:
            return False
        # The tail must begin exactly where the SCOPE ends.
        return len(scope) == (2 if scope[0] == "agent" else 1)
    return False

# (There is deliberately no CATEGORY_SCOPES constant. The scope dispatch in
# :func:`key_validity` is an explicit if-chain on the head token, and the
# category test runs on the TAIL via :func:`_looks_like_category`, so a set of
# "scopes that may carry a category" has no consumer. It existed briefly and was
# DELETED rather than kept as an unused declaration — an unwired constant reads
# as a contract something is supposed to honour.)

# ---------------------------------------------------------------------------
# meta.* — the RO families (spec §0, §2c, §2d)
# ---------------------------------------------------------------------------

DECLARED_META_RUNTIME_LEAVES: Final[frozenset[str]] = frozenset({
    "ws_root", "ws_name", "project_type",
})
# The COLLAPSE outputs (spec §1A): folded AFTER every scope resolves, not at the L0.2
# treewalk above — which is why they are their OWN group. ⚑ ALL FOUR ARE PRODUCED,
# on the launch path (`commands/start.py._install_assembly_collapse`); the copy output
# split into `seeded` + `synced` on 2026-08-10, retiring the reserved `backup`, and
# `env` — the VAR slots after write-once arbitration — joined on 2026-08-14.
DECLARED_META_ASSEMBLY_LEAVES: Final[frozenset[str]] = frozenset({
    "bindings", "seeded", "synced", "env",
})
DECLARED_META_WORKSET_LEAVES: Final[frozenset[str]] = frozenset({
    "path", "name", "settings",
})
# ⚑ `home` IS produced — `settings_launch.workset_anchor_floor`, beside the
# `@meta.box.path` it derives from — and it is the ONLY spelling of that
# derivation: home does NOT route through `bindings.rw` (spec `:1015`), so the
# assembly seam builds the pid-0 foundation bind by READING this key, and every
# launch's home mount resolves through it.
# ⚑ The last 2 have NO PRODUCER: `container_name` renders in
# `utils.container_name_for`, off proj attrs, not the store; `helper_num` travels
# in helper messages. Declared-but-unproduced is the state the manifest already
# describes (JC-B2-3), not an omission.
DECLARED_META_BOX_LEAVES: Final[frozenset[str]] = frozenset({
    "path", "name", "mode", "workspace", "settings",
    "inbox", "share_global", "share_workset",
    "home", "container_name", "helper_num",
})
DECLARED_META_BOX_AUTH_LEAVES: Final[frozenset[str]] = frozenset({"workset_path"})
DECLARED_META_AGENT_LEAVES: Final[frozenset[str]] = frozenset({
    "name", "path", "settings", "mode", "exec",
})
DECLARED_META_AGENT_AUTH_LEAVES: Final[frozenset[str]] = frozenset({"share_support"})

# ---------------------------------------------------------------------------
# Reserved leaf names (spec §0)
# ---------------------------------------------------------------------------

#: Names a leaf key may NOT be called, because each would shadow a REAL attribute
#: on the resolved store — a collision-safety floor on the resolved data structure
#: (spec §0). Two kinds, one rule: the public (non-dunder) ``dict`` methods, plus
#: the store's own public class members (``RESERVED_KEY_NAMES``,
#: ``insert_segments``), neither of which can be spelled as a dunder and so each
#: names itself. Matched CASE-SENSITIVELY.
#: ⚑ ONE SET, TWO POSITIONS — and the second half is what the shared object does NOT
#: buy. This IS ``KeyStore.RESERVED_KEY_NAMES`` (identity, not a copy), so the NAMES
#: cannot drift; the two floors still APPLY them differently. This module judges the
#: LEAF alone (:func:`_leaf` -> :func:`leaf_name_reason`), named in this module's
#: vocabulary ("leaf" for what the store calls a key), while ``KeyStore.__setitem__``
#: judges EVERY SEGMENT it writes. The store is therefore STRICTLY STRICTER: a leaf
#: this floor refuses is a segment the store refuses too, and the gap runs one way —
#: ``agent.items.model`` is a KEY here (given an agent literally named ``items``) and
#: unwritable there. A NARROWER SUBSET, not a disagreement; the direction is pinned by
#: ``tests/test_settings/test_settings_keyspace.py`` so it cannot silently invert.
#: ⚑ AND THE ORDER IS WHY THIS FLOOR IS NOT REDUNDANT. For a FILE-authored key the
#: store speaks FIRST — ``settings_assemble._parse_naming_file`` builds the
#: ``KeyStore`` and raises before ``merge`` or any resolve — so the reserved arm of
#: :func:`key_validity` never runs on that path. It earns its keep everywhere nothing
#: has been written to a store yet — the file-scope READ gates
#: (``config_keys.scope_read_key_error``), the CLI level's own guard
#: (``settings_cli_level.guard_cli_level``), and the ``<scope>.env.<VAR>`` WRITE gate
#: (``config_keys.scope_env_var_error``, which is the "rejected loudly at
#: write/``config set`` time" half spec §0 asks for). All three were MEASURED speaking.
RESERVED_LEAF_NAMES: Final[frozenset[str]] = KeyStore.RESERVED_KEY_NAMES

_DUNDER_RE: Final = re.compile(r"^__.*__$")

#: ``env.<VAR>`` / ``secret_path.<VAR>`` variable-name shape (spec §2a; mirrors
#: ``settings_categories.SECRET_VAR_RE`` — kept as its own compiled copy so this
#: module's only settings-stack imports stay ``keystore`` / ``kb_store``, the
#: leaves at the bottom of the stack).
_VAR_RE: Final = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# ---------------------------------------------------------------------------
# Keys the ARC is mid-retiring (the conformance-test exemptions)
# ---------------------------------------------------------------------------

#: Spellings still present in ``config_keys.KNOWN_CONFIG_KEYS`` that the
#: SPEC has already retired or renamed. Each names the phase that deletes it.
#: ``tests/test_settings_keyspace.py`` exempts exactly these and nothing else —
#: **a SECOND entry means the spec and the settable surface disagree somewhere
#: this arc has not accounted for, and that is a STOP-and-report condition, not
#: an exemption to add.**  (It held THREE until P7 retired ``box.agent_name`` and
#: ``system.default_agent``; the cap shrinks with the set, deliberately.)
#:
#: The "closed-keyspace resolve enforcement" follow-on was gated on this set being
#: EMPTY (plus: the conformance test green with no exemptions, and a real-store sweep
#: per migration-issues M-1/M-2). ⚑ IT IS TAKEN — ``settings_launch`` refuses at the
#: resolve seam — on the first two conditions; the real-store sweep was WAIVED rather
#: than run, and that is where the residual risk sits.
#: ⚑ NOW **EMPTY** (C-CANON seeds half, 2026-08-01): M-11 renamed
#: ``system.base_template`` → ``system.template`` and dropped the old spelling from
#: ``KNOWN_CONFIG_KEYS``, so the spec and the settable surface agree with no
#: exemptions. An entry appearing here again means a NEW divergence, which is a
#: STOP-and-report condition, not a line to add.
RETIRING_KEYS: Final[frozenset[str]] = frozenset()


# ---------------------------------------------------------------------------
# The validator
# ---------------------------------------------------------------------------


class KeyClass(enum.Enum):
    """What a dotted path IS to the closed keyspace. THREE answers, not two.

    ⚑⚑ THE THIRD ONE IS THE POINT. A path can fail to be a key for two opposite
    reasons, and collapsing them is how a NAMESPACE gets reported as a fabrication:

    ``KEY``         a declared key. Readable, resolvable; may be settable.
    ``NAMESPACE``   a declared INTERIOR of the keyspace — a grouping declared keys
                    hang under. ``meta`` (spec :42, *"a TOP-LEVEL, protected
                    read-only namespace, grouped as meta.<scope>.*"*), a scope
                    root, an agent tier, an ``auth``/``channels`` sub-table. NOT a
                    key, and never settable — but a NODE here is legitimate store
                    structure, not something the code invented.
    ``UNDECLARED``  neither. Spec §0's error case: *"reading, setting, or resolving
                    an undeclared key is an ERROR that NAMES the offending key"*.

    ⚑ An ENUM rather than :class:`Verdict`'s string constants because nothing
    subclasses this and nothing may add a fourth answer — a name-keyed
    ``EXEMPT`` is exactly the carve-out the closed keyspace exists to refuse.
    """

    KEY = "KEY"
    NAMESPACE = "NAMESPACE"
    UNDECLARED = "UNDECLARED"


class KeyJudgement(NamedTuple):
    """A :class:`KeyClass` and the REASON, which is empty only for ``KEY``.

    Every non-key answer carries prose because every consumer must be able to tell
    the user WHY (spec §2h: *"the error NAMES which key, at which level, and
    WHY"*). ⚑ The reason is for the READER; nothing may branch on its text.
    """

    cls: KeyClass
    reason: str


#: The one ``KEY`` judgement — there is nothing to say about a key that is a key.
_KEY: Final[KeyJudgement] = KeyJudgement(KeyClass.KEY, "")


def _namespace(reason: str) -> KeyJudgement:
    return KeyJudgement(KeyClass.NAMESPACE, reason)


def _undeclared(reason: str) -> KeyJudgement:
    return KeyJudgement(KeyClass.UNDECLARED, reason)


def _leaf(leaf: str) -> KeyJudgement:
    """A declared leaf, subject to the reserved-name floor."""
    reason = leaf_name_reason(leaf)
    return _KEY if reason is None else _undeclared(reason)


def leaf_name_reason(leaf: str) -> str | None:
    """Reject a RESERVED / dunder leaf name (spec §0).

    PUBLIC because the floor is due at TWO moments, not one: spec §0 says a
    reserved name is "rejected loudly at write/``config set`` time", so the
    ``<scope>.env.<VAR>`` set/reset route calls this directly
    (``config_keys.scope_env_var_error``) rather than waiting for the
    resolve-time :func:`key_validity` pass — a stored key that only fails at the
    NEXT launch is exactly the deferred surprise §0 forbids.
    """
    if leaf in RESERVED_LEAF_NAMES:
        return (
            f"'{leaf}' is a RESERVED key name — it would shadow a real attribute on "
            f"the resolved store — and may not name a key (spec §0 reserved key names)"
        )
    if _DUNDER_RE.match(leaf):
        return (
            f"'{leaf}' matches the dunder pattern and may not name a key "
            f"(spec §0 reserved key names)"
        )
    return None


def is_valid_agent_segment(segment: str, valid_agents: Collection[str]) -> bool:
    """Is *segment* a legal ``agent.<HERE>`` discriminator?

    ``default`` (the agent tier's all-agents FALLBACK, §2) or a member
    of *valid_agents*. The caller decides what "valid agent" means — see
    ``settings_prefs.default_valid_agents``, which answers it as "a discovered
    harness, or a persona node whose harness is discovered" (§2h: the
    test is *is it a VALID agent*, NOT *is it the ACTIVE agent*).
    """
    return segment == "default" or segment in valid_agents


def _category_reason(
    prefix: str, rest: list[str], *, what: str
) -> KeyJudgement:
    """Judge a ``<category>.<name>`` tail under an already-valid *prefix*.

    *rest* is the tail AFTER the scope token(s). *what* names the scope for the
    message ("the box scope", "agent 'claude'", …).

    ⚑ Two of these categories have an INTERIOR: ``env`` and ``secret_path`` are
    VAR-keyed, so the bare token is a namespace real keys hang under, and
    ``bindings`` is the arm root. The dest-keyed terminals have none — the
    category token IS the key, and anything under it is a value address.
    """
    if not rest:
        # Unreachable from either caller (both gate on a non-empty tail), and kept
        # rather than deleted because it is the correct answer if one ever stops.
        return _namespace(f"'{prefix}' names {what} itself, which is not a key")
    head = rest[0]

    # masks — the value-less keyed category (spec §2a). The KEY is exactly
    # ``<scope>.masks``; entries live INSIDE it as a dict[box_dest -> bool|None],
    # and a box_dest is a PATH, not a key segment, so a dotted tail under masks is
    # a value address rather than a key. Accept the bare form only.
    # ⚑ This, the ``bindings.{ro,rw}`` branch and the four-category branch below
    # are ALL terminal dest-keyed; they are enumerated in
    # :data:`TERMINAL_CATEGORY_TAILS`.
    if head == "masks":
        if len(rest) == 1:
            return _KEY
        return _undeclared(
            f"'{prefix}.masks.{'.'.join(rest[1:])}' is not a key: masks is a "
            f"keyed category whose entries are box destinations inside the "
            f"'{prefix}.masks' value, not key segments (spec §2a)"
        )

    # env.<VAR> / secret_path.<VAR> — scalar-valued, VAR-keyed (spec §2a).
    if head in ("env", "secret_path"):
        if len(rest) == 1:
            # The VAR-keyed family's ROOT. Real keys live one segment below it, so
            # the node is structure; only a SCALAR sitting here is a fabrication.
            return _namespace(
                f"'{prefix}.{head}' is a namespace, not a key: {head} is keyed per "
                f"variable — '{prefix}.{head}.<VAR>' (spec §2a)"
            )
        if len(rest) != 2:
            return _undeclared(
                f"'{prefix}.{'.'.join(rest)}' is not a key: {head} is keyed per "
                f"variable — '{prefix}.{head}.<VAR>' (spec §2a)"
            )
        var = rest[1]
        if not _VAR_RE.match(var):
            return _undeclared(
                f"'{var}' is not a legal environment variable name for "
                f"'{prefix}.{head}.<VAR>' (spec §2a)"
            )
        return _leaf(var)

    # bindings.{ro,rw} — DEST-KEYED and TERMINAL (spec §2a; R-5/R-10,
    # 2026-08-06c), the same shape as ``masks`` above. TWO independent rules:
    #
    # 1. The ARM is REQUIRED (§2d: an ARM-LESS binding is not a declared key) —
    #    ``bindings`` alone names the arm ROOT, not a key.
    # 2. The ARM is the WHOLE of the key. Entries live INSIDE its value as a
    #    dict[box_dest -> [src[, options]]], and a box_dest is a PATH, so a tail
    #    under an arm is a VALUE address rather than a key. There is no entry
    #    NAME at all any more (R-10: the destination IS the identity).
    if head == "bindings":
        if len(rest) == 1:
            # The ARM ROOT. Rule 1 still holds — an arm-LESS binding is not a key —
            # but the node itself is where the two arms live, so it is structure.
            return _namespace(
                f"'{prefix}.bindings' is a namespace, not a key: bindings are "
                f"declared per ARM — '{prefix}.bindings.ro' / "
                f"'{prefix}.bindings.rw' (spec §2a / §2d)"
            )
        if rest[1] not in ("ro", "rw"):
            return _undeclared(
                f"'{prefix}.{'.'.join(rest)}' is not a key: bindings are declared "
                f"per ARM — '{prefix}.bindings.ro' / "
                f"'{prefix}.bindings.rw' (spec §2a / §2d)"
            )
        if len(rest) == 2:
            return _KEY
        return _undeclared(
            f"'{prefix}.bindings.{rest[1]}.{'.'.join(rest[2:])}' is not a key: "
            f"'{prefix}.bindings.{rest[1]}' is a TERMINAL dest-keyed key whose "
            f"entries are box destinations inside its value, not key segments. "
            f"Bindings have no entry NAME — write the entry in the settings FILE "
            f"under '{prefix}.bindings.{rest[1]}', keyed by its destination "
            f"(spec §2a)"
        )

    # caches / seeded / common / synced — DEST-KEYED and TERMINAL (spec §2a;
    # 2026-08-08c), the same shape as ``masks`` and the ``bindings`` arms above,
    # but terminal ONE SEGMENT SHALLOWER: the category token IS the whole key.
    # Entries live INSIDE its value as a dict[box_dest -> [src[, options]]], and a
    # box_dest is a PATH, so a tail under one is a VALUE address, not a key. There
    # is no entry NAME at all any more — the destination IS the identity.
    if head in {c for c in BIND_CATEGORIES if "." not in c}:
        if len(rest) == 1:
            return _KEY
        return _undeclared(
            f"'{prefix}.{head}.{'.'.join(rest[1:])}' is not a key: "
            f"'{prefix}.{head}' is a TERMINAL dest-keyed key whose entries are "
            f"box destinations inside its value, not key segments. "
            f"'{head}' entries have no NAME — write the entry in the settings "
            f"FILE under '{prefix}.{head}', keyed by its destination (spec §2a)"
        )

    # Unreachable BY CONSTRUCTION: the branches above cover exactly the token set
    # :func:`_looks_like_category` admits, and no caller enters without it.
    raise AssertionError(f"{head!r} passed _looks_like_category with no branch here")


def _is_category_token(token: str) -> bool:
    """Is *token* a §2a category token?

    ⚑ DERIVED FROM THE DELIVERY TABLE, never hand-listed (P13):
    :data:`~kanibako.settings.settings_categories.CATEGORY_FAMILY_ROOTS` is the one
    place all NINE families are named, so a tenth is a category token here with no
    edit — which matters because TWO different questions read this: where a category
    tail begins (:func:`_looks_like_category`) and which segments can never be an
    AGENT NAME (:func:`_could_name_an_agent`).

    🛑 IT IS NOT :data:`BIND_CATEGORIES`, and that is the correction. This used to
    read the bind-shaped set and then NAME ``masks``, ``env`` and ``secret_path``
    beside it, so "derived" held only for a family that happens to be bind-shaped —
    a tenth family with a value shape of its own would have reached ``agent.<HERE>``
    as a candidate AGENT NAME and been conceded. No live hole (all eight roots
    refuse today), but the guarantee the shape claimed was not the one it gave.
    """
    return token in CATEGORY_FAMILY_ROOTS


def _looks_like_category(rest: list[str]) -> bool:
    """Does *rest* start with a §2a category token?"""
    return bool(rest) and _is_category_token(rest[0])


def _could_name_an_agent(segment: str) -> bool:
    """Could *segment* EVER be the ``agent.<HERE>`` discriminator of a real agent?

    ⚑ THIS IS THE CONCESSION'S TEST, and it is NOT "is this agent installed"
    (:func:`key_class`). A machine cannot enumerate the agents it has never heard
    of, so an unrecognised NAME has to be conceded — but the tokens below are a
    KNOWN FINITE SET the keyspace declares itself, so there is nothing unknowable
    about them and conceding one would un-arm §0 over a shape that is documented as
    a RELIC (``agent.common.plugins``, ``agent.env.<VAR>``, ``agent.seeded.*`` — the
    undiscriminated launch-built form, MIGRATION.md §2.11).

    FALSE for a §2a category token and for ``default``; both are then judged by the
    core contract, which knows them. TRUE for anything else — including a
    plausible-looking typo such as ``agent.clade.zippity``, which is the IRREDUCIBLE
    residual: ``clade`` is exactly the shape a real uninstalled harness has.
    """
    return segment != "default" and not _is_category_token(segment)


def _scope_reason(
    scope: str,
    rest: list[str],
    *,
    leaves: frozenset[str],
    sub_tables: dict[str, frozenset[str]],
    what: str,
) -> KeyJudgement:
    """Judge a NON-agent scope key ``<scope>.<rest…>``."""
    if not rest:
        # The SCOPE TABLE itself. A settings file's ``box:`` heading writes this
        # node; it is the grouping every scope key hangs under, never a key.
        return _namespace(
            f"'{scope}' names the {what} scope, which is a namespace, not a key "
            f"(spec §0)"
        )
    if _looks_like_category(rest):
        return _category_reason(scope, rest, what=what)
    if len(rest) == 1:
        if rest[0] in leaves:
            return _leaf(rest[0])
        if rest[0] in sub_tables:
            # A declared SUB-TABLE root (``<scope>.auth``, ``<scope>.channels``).
            # ⚑ THE MEMBER LIST IS DELIBERATELY NOT PRINTED HERE: a namespace
            # message's job is "this is not a key", and the leaf that is actually
            # wrong gets the list from the branch below. Naming the members twice is
            # P12 padding.
            return _namespace(f"'{scope}.{rest[0]}' is a namespace, not a key")
        return _undeclared(
            f"'{rest[0]}' is not a declared {what} key (declared: "
            f"{', '.join(sorted(leaves))}, plus the §2a categories)"
        )
    if len(rest) == 2 and rest[0] in sub_tables:
        table = sub_tables[rest[0]]
        if rest[1] in table:
            return _leaf(rest[1])
        return _undeclared(
            f"'{scope}.{rest[0]}.{rest[1]}' is not a declared key (declared "
            f"'{scope}.{rest[0]}.*': {', '.join(sorted(table))})"
        )
    return _undeclared(
        f"'{scope}.{'.'.join(rest)}' is not a declared {what} key "
        f"(spec §0 — the keyspace is CLOSED)"
    )


def _meta_reason(
    rest: list[str],
    valid_agents: Collection[str],
    leaves: Collection[str] = DECLARED_AGENT_LEAVES,
) -> KeyJudgement:
    """Judge a ``meta.<rest…>`` key (spec §0, §2c, §2d).

    ⚑ EVERY GROUP HEAD IS A NAMESPACE, and saying so is not a courtesy: spec :42
    declares ``meta.*`` *"a TOP-LEVEL, protected (read-only) namespace, grouped as
    ``meta.<scope>.*``"* — the grouping is the spec's own word for these nodes.
    """
    if not rest:
        return _namespace("'meta' is a namespace, not a key")
    group = rest[0]
    tail = rest[1:]

    if group == "runtime":
        if not tail:
            return _namespace("'meta.runtime' is a namespace, not a key")
        if len(tail) == 1 and tail[0] in DECLARED_META_RUNTIME_LEAVES:
            return _KEY
        return _undeclared(
            f"'meta.runtime.{'.'.join(tail)}' is not a declared key (declared: "
            f"{', '.join(sorted(DECLARED_META_RUNTIME_LEAVES))})"
        )

    if group == "assembly":
        if not tail:
            return _namespace("'meta.assembly' is a namespace, not a key")
        if len(tail) == 1 and tail[0] in DECLARED_META_ASSEMBLY_LEAVES:
            return _KEY
        return _undeclared(
            f"'meta.assembly.{'.'.join(tail)}' is not a declared key (declared: "
            f"{', '.join(sorted(DECLARED_META_ASSEMBLY_LEAVES))})"
        )

    if group == "workset":
        if not tail:
            return _namespace("'meta.workset' is a namespace, not a key")
        if len(tail) == 1 and tail[0] in DECLARED_META_WORKSET_LEAVES:
            return _KEY
        return _undeclared(
            f"'meta.workset.{'.'.join(tail)}' is not a declared key (declared: "
            f"{', '.join(sorted(DECLARED_META_WORKSET_LEAVES))})"
        )

    if group == "box":
        if not tail:
            return _namespace("'meta.box' is a namespace, not a key (spec §0)")
        if len(tail) == 1 and tail[0] in DECLARED_META_BOX_LEAVES:
            return _KEY
        if len(tail) == 1 and tail[0] == "auth":
            return _namespace("'meta.box.auth' is a namespace, not a key")
        if len(tail) == 2 and tail[0] == "auth":
            if tail[1] in DECLARED_META_BOX_AUTH_LEAVES:
                return _KEY
            return _undeclared(
                f"'meta.box.auth.{tail[1]}' is not a declared key (declared: "
                f"{', '.join(sorted(DECLARED_META_BOX_AUTH_LEAVES))})"
            )
        if tail[0] == "agent":
            # meta.box.agent.<key> — the RO MIRROR that gives a box a STATIC,
            # declarable key path to an ACTIVE-agent value (spec :1077, *"the
            # meta.box.agent.<key> mirror pattern → avoids a nested dynamic
            # lookup"*): a symbol inside a key SEGMENT would need a grammar the key
            # system does not have.
            #
            # ⚑ TWO SOURCES, both DECLARED, and both are the mirror's job ([R141] as
            # amended): the settable ``agent.<agent>`` contract (:859), PLUS
            # ``auth.*`` capabilities that have no settable form (:1081 declares
            # ``meta.box.agent.auth.share_support`` as its own row). The ``auth``
            # leaves are the ``meta.agent`` tier's, so they come from
            # :data:`DECLARED_META_AGENT_AUTH_LEAVES` and are answered here rather
            # than by :func:`_agent_tail_reason`, which knows only the first source.
            # ``auth_chain_floor`` writes that leaf on every launch resolve.
            mirror = tail[1:]
            if len(mirror) == 1 and mirror[0] == "auth":
                return _namespace("'meta.box.agent.auth' is a namespace, not a key")
            if len(mirror) == 2 and mirror[0] == "auth":
                if mirror[1] in DECLARED_META_AGENT_AUTH_LEAVES:
                    return _KEY
                return _undeclared(
                    f"'meta.box.agent.auth.{mirror[1]}' is not a declared key "
                    f"(declared: "
                    f"{', '.join(sorted(DECLARED_META_AGENT_AUTH_LEAVES))})"
                )
            return _agent_tail_reason("meta.box.agent", mirror, leaves)
        return _undeclared(
            f"'meta.box.{'.'.join(tail)}' is not a declared key (declared: "
            f"{', '.join(sorted(DECLARED_META_BOX_LEAVES))}, auth.workset_path, "
            f"and the agent.* read-back mirror)"
        )

    if group == "agent":
        if not tail:
            return _namespace("'meta.agent' is a namespace, not a key (spec §2d)")
        name = tail[0]
        if not is_valid_agent_segment(name, valid_agents):
            return _undeclared(_bad_agent_reason(name, valid_agents))
        sub = tail[1:]
        if not sub:
            # ⚑ THE OTHER NAMESPACE ONE WORD AWAY ([R141]): this is the agent's own
            # ANCHOR group; ``meta.box.agent`` above is the RO mirror of the settable
            # contract. Two namespaces, one word apart — say which, never both.
            return _namespace(f"'meta.agent.{name}' is a namespace, not a key")
        if len(sub) == 1 and sub[0] in DECLARED_META_AGENT_LEAVES:
            return _KEY
        if len(sub) == 1 and sub[0] == "auth":
            # The tier the ``meta.box.agent.auth`` mirror points AT (spec :1081).
            return _namespace(f"'meta.agent.{name}.auth' is a namespace, not a key")
        if len(sub) == 2 and sub[0] == "auth":
            if sub[1] in DECLARED_META_AGENT_AUTH_LEAVES:
                return _KEY
            return _undeclared(
                f"'meta.agent.{name}.auth.{sub[1]}' is not a declared key "
                f"(declared: {', '.join(sorted(DECLARED_META_AGENT_AUTH_LEAVES))})"
            )
        return _undeclared(
            f"'meta.agent.{name}.{'.'.join(sub)}' is not a declared key "
            f"(declared: {', '.join(sorted(DECLARED_META_AGENT_LEAVES))}, "
            f"auth.share_support)"
        )

    return _undeclared(
        f"'meta.{group}' is not a declared meta group (declared: runtime, "
        f"assembly, workset, box, agent)"
    )


def _bad_agent_reason(name: str, valid_agents: Collection[str]) -> str:
    known = ", ".join(sorted({*valid_agents, "default"})) or "default"
    return (
        f"'{name}' is not a valid agent (valid: {known}). The agent segment of "
        f"an agent-scope key must name a real agent or the 'default' fallback "
        f"tier (spec §2d / §0 L21 — a bare 'agent.<key>' is not a key)"
    )


class _EffectiveLeaves(Collection[str]):
    """The core §2d set with the PLUGIN-declared set behind it — unioned LAZILY.

    ⚑ THE UNION IS THE COST, and materialising it eagerly made every judgement pay
    it. The plugin set's one production supplier (``settings_keyspace_probe``)
    answers by IMPORTING every installed plugin, and those modules parse YAML in
    their module bodies; ``key_class`` used to build
    ``frozenset(DECLARED_AGENT_LEAVES) | frozenset(agent_leaves)`` before dispatching
    on the head, so a ``box.image`` resolve paid for a question only an ``agent.*``
    leaf can ask. Asking the CORE set first defers the plugin question to a leaf the
    core contract does not declare, which is the only leaf a plugin can answer for.

    ⚑ ITERATION STILL FORCES THE UNION, and that is right: the only iterating caller
    is the refusal message's ``sorted(leaves)`` in :func:`_agent_tail_reason`, which
    is already on its way to UNDECLARED — the vocabulary it names the user has to be
    the real one, so the cost is owed there.
    """

    __slots__ = ("_plugins",)

    def __init__(self, plugins: Collection[str]) -> None:
        self._plugins = plugins

    def _union(self) -> "frozenset[str]":
        return frozenset(DECLARED_AGENT_LEAVES) | frozenset(self._plugins)

    def __contains__(self, item: object) -> bool:
        return item in DECLARED_AGENT_LEAVES or item in self._plugins

    def __iter__(self) -> Iterator[str]:
        return iter(self._union())

    def __len__(self) -> int:
        return len(self._union())


def effective_agent_leaves(
    agent_leaves: "Collection[str] | None",
) -> Collection[str]:
    """The core §2d contract with the PLUGIN-declared *agent_leaves* behind it (§0).

    ``None`` means core alone.  THE constructor for :class:`_EffectiveLeaves`, and it is
    public because the effective vocabulary has TWO consumers that must not disagree:
    :func:`key_class`, which JUDGES a key, and ``config_keys._PERSONA_STATE_LEAVES``,
    which RECOGNISES the per-node spelling before any verb dispatches on it.  They were
    two sets until 2026-08-29 — the judge unioned the plugin leaves and the recogniser
    did not, so ``agent.goose.provider`` was a declared key at the ``agent`` noun and
    "unknown config key" at ``system set`` (measured).
    ⚑ The laziness is the contract, not an optimisation: see :class:`_EffectiveLeaves`.
    """
    return (
        DECLARED_AGENT_LEAVES if agent_leaves is None
        else _EffectiveLeaves(agent_leaves)
    )


def _leaves_are_known() -> bool:
    """The default *leaves_known*: a caller that says nothing covers every agent."""
    return True


def _agent_tail_reason(
    prefix: str,
    tail: list[str],
    leaves: Collection[str] = DECLARED_AGENT_LEAVES,
    *,
    leaves_known: Callable[[], bool] = _leaves_are_known,
) -> KeyJudgement:
    """Judge the tail of an agent-scope key, after the discriminator.

    *leaves* is the effective agent-leaf set: the core §2d contract UNIONED with
    what the PLUGINS declare (§0 — *"Agent specifics are PLUGIN-declared
    … Every non-universal specific is established AND modified by the PLUGIN,
    never hardcoded in core"*). Without the union a real plugin key is refused:
    goose declares ``provider`` through ``setting_descriptors()`` and it is a
    legitimate ``agent.goose.provider``.

    ⚑ *leaves_known* answers FALSE when the caller could not read this agent's plugin
    at all, so *leaves* does not cover it — see :func:`key_class`. Then the VOCABULARY
    is conceded and nothing else: the SHAPE rules below still apply (a category tail
    is judged, a multi-segment tail is still not an agent key), and so does the
    reserved-name floor inside :func:`_leaf`, because that floor is about colliding
    with the resolved store rather than about what a plugin declares.

    ⚑⚑ IT IS A CALLABLE, AND ASKED LAST, FOR THE REASON :class:`_EffectiveLeaves`
    GIVES. Its production supplier answers by importing every installed plugin, so
    evaluating it to a ``bool`` at the call site re-arms on ``agent.<agent>.*`` the
    whole cost the lazy union defers — ``agent.claude.model``, a plain core leaf,
    would still pay it. Both operands are PURE, so the disjunction below answers the
    same whichever is asked first; only the COST differs.
    """
    if not tail:
        # An agent TIER — ``agent.<agent>``, ``agent.default``, or the
        # ``meta.box.agent`` mirror. The tier is where the leaves hang, so the node
        # is store structure; only a SCALAR sitting on a tier is a fabrication.
        return _namespace(f"'{prefix}' names an agent tier, not a key (spec §2d)")
    if _looks_like_category(tail):
        return _category_reason(prefix, tail, what=f"'{prefix}'")
    if len(tail) == 1:
        # ⚑ CORE FIRST, PLUGINS SECOND, THE CONCESSION LAST — cost order, not rule
        # order. ``leaves`` asks :data:`DECLARED_AGENT_LEAVES` before the plugin set
        # it wraps, and ``leaves_known`` is only called when both have missed.
        if tail[0] in leaves or not leaves_known():
            return _leaf(tail[0])
        return _undeclared(
            f"'{tail[0]}' is not a declared agent key (declared: "
            f"{', '.join(sorted(leaves))}, plus the §2a "
            f"categories) (spec §0 — the keyspace is CLOSED)"
        )
    return _undeclared(
        f"'{prefix}.{'.'.join(tail)}' is not a declared agent key "
        f"(spec §0 — the keyspace is CLOSED)"
    )


def key_validity(
    key: str,
    *,
    valid_agents: Collection[str],
    agent_leaves: "Collection[str] | None" = None,
) -> str | None:
    """``None`` when *key* is a legal key under §0; else a REASON naming why not.

    ⚑ THE KEY-OR-NOT VIEW of :func:`key_class`, and the one every SET boundary
    wants: at a write site a NAMESPACE and a fabrication are equally not-a-key, so
    both come back as a reason. A consumer that must tell the two apart — only the
    store-path classifier does — calls :func:`key_class` instead.

    A REASON string rather than a bool because every consumer must be able to
    tell the user WHY (spec §2h: *"the error NAMES which key, at which
    level, and WHY"*, and §0: an undeclared key errors NAMING the key).
    """
    judgement = key_class(
        key, valid_agents=valid_agents, agent_leaves=agent_leaves,
    )
    return None if judgement.cls is KeyClass.KEY else judgement.reason


def key_class(
    key: str,
    *,
    valid_agents: Collection[str],
    agent_leaves: "Collection[str] | None" = None,
    agents_with_known_leaves: "Container[str] | None" = None,
) -> KeyJudgement:
    """*key*'s :class:`KeyClass` under §0, with the REASON for a non-key.

    *valid_agents* is injected (purity) — the set of agent discriminators that
    are real, exclusive of ``"default"`` which is always legal. *agent_leaves*
    likewise injects the PLUGIN-declared agent keys to union over the core §2d
    set (``None`` = core only); see :func:`_agent_tail_reason`.
    ⚑ *agent_leaves* is ASKED, NEVER MATERIALISED HERE. Its production supplier
    discovers plugins on the first question put to it, so a ``frozenset(...)`` around
    it charges every path judged — ``config.*``, ``box.*``, a bare namespace — for a
    vocabulary only an agent LEAF can consult. :class:`_EffectiveLeaves` carries the
    measurement.

    ⚑ *agents_with_known_leaves* names the agents *agent_leaves* actually COVERS.
    ``None`` (the default) means it covers every agent, which is what a caller
    judging only agents it can see wants. Naming a set instead concedes the LEAVES
    of any agent outside it, because the two are a DEPENDENT PAIR: an agent's leaf
    vocabulary is its plugin's, so an agent whose plugin the caller could not read
    has NO knowable vocabulary, and judging one against a set that cannot contain it
    refuses a key that is genuinely declared. ``agent.goose.provider`` is the
    measured case — a real goose ``setting_descriptor`` leaf, refused as "not a
    declared agent key" on a machine without goose installed.
    ⚑ It is a ``Container`` rather than a ``Collection`` because only membership is
    asked: the supplier for the resolve seam answers through the agent-ref grammar
    (a persona is known iff its HARNESS is), which nothing can enumerate. ⚑ It is
    never asked about ``default`` — see the call site.
    🛑 It does NOT reach ``meta.agent.<agent>.*``. That tier's vocabulary is
    core-declared (:data:`DECLARED_META_AGENT_LEAVES` + ``auth.share_support``) and
    no plugin extends it, so it is knowable whether or not the plugin is here —
    there is nothing to concede.

    The dispatch is on the FIRST segment; every branch reports against the
    spec section that declares the family.
    """
    if not key or not isinstance(key, str):
        return _undeclared("the empty string is not a key")
    parts = key.split(".")
    if any(seg == "" for seg in parts):
        return _undeclared(
            f"'{key}' has an empty path segment; a key is dot-separated "
            f"non-empty segments (spec §0)"
        )
    head, rest = parts[0], parts[1:]
    # ⚑ LAZY, and the dispatch below is why: only the agent tail asks about leaves,
    # and materialising the union here charged every ``box.*`` / ``system.*`` /
    # ``meta.*`` path for a plugin import it never uses. See :class:`_EffectiveLeaves`.
    leaves: Collection[str] = effective_agent_leaves(agent_leaves)

    if head == "config":
        if not rest:
            return _namespace("'config' is a namespace, not a key (spec §1)")
        if len(rest) == 1 and rest[0] in DECLARED_CONFIG_LEAVES:
            return _KEY
        return _undeclared(
            f"'{key}' is not a declared Layer-1 config key (declared: "
            f"{', '.join('config.' + k for k in sorted(DECLARED_CONFIG_LEAVES))})"
        )

    if head == "meta":
        return _meta_reason(rest, valid_agents, leaves)

    if head == "pref":
        # pref.<target-key> (spec §2h). The family is valid iff the TARGET is a
        # valid key. Whether it may be REQUESTED is a separate question the
        # allowlist + forbidden tiers answer (settings_prefs) — this is only
        # "is it a key".
        if not rest:
            return _namespace("'pref' is a namespace, not a key (spec §2h)")
        if rest[0] == "pref":
            return _undeclared(
                "'pref.pref.…' is not a key: a request-of-a-request has no "
                "termination argument (spec §2h categorical tier)"
            )
        # ⚑ THE TARGET'S CLASS IS INHERITED, all three of them: ``pref.box`` is the
        # request-side spelling of a namespace, and a resolved store really does
        # carry those nodes (``pref.agent.<a>`` above a requested leaf).
        # ⚑⚑ EVERY ORACLE PARAMETER RIDES ALONG. Dropping one makes the SAME key
        # answer differently by SPELLING — ``agent.goose.zippity`` conceded while
        # ``pref.agent.goose.zippity`` refused — which is not a stricter pref rule,
        # it is two keyspaces. ``agents_with_known_leaves`` was the omission, and it
        # was invisible because ``apply_prefs`` happens to pre-filter on a
        # coinciding set; the agreement is pinned rather than left to that.
        inner = key_class(
            ".".join(rest),
            valid_agents=valid_agents,
            agent_leaves=agent_leaves,
            agents_with_known_leaves=agents_with_known_leaves,
        )
        if inner.cls is KeyClass.KEY:
            return _KEY
        if inner.cls is KeyClass.NAMESPACE:
            return _namespace(f"its target names a namespace — {inner.reason}")
        return _undeclared(f"its target is not a declared key — {inner.reason}")

    if head == "system":
        return _scope_reason(
            "system", rest,
            leaves=DECLARED_SYSTEM_LEAVES,
            sub_tables={
                "channels": DECLARED_SYSTEM_CHANNEL_LEAVES,
                "auth": DECLARED_SYSTEM_AUTH_LEAVES,
            },
            what="system",
        )

    if head == "workset":
        return _scope_reason(
            "workset", rest,
            leaves=DECLARED_WORKSET_LEAVES,
            sub_tables={
                "channels": DECLARED_WORKSET_CHANNEL_LEAVES,
                "auth": DECLARED_WORKSET_AUTH_LEAVES,
            },
            what="workset",
        )

    if head == "box":
        return _scope_reason(
            "box", rest,
            leaves=DECLARED_BOX_LEAVES,
            sub_tables={"auth": DECLARED_BOX_AUTH_LEAVES},
            what="box",
        )

    if head == "agent":
        # The agent tier is DISCRIMINATED — ``agent.<agent>`` or
        # ``agent.default`` (spec §2d, §0). A bare ``agent.<key>`` is
        # NOT a key, and the code must REFUSE it rather than quietly accept it.
        if not rest:
            return _namespace("'agent' is a namespace, not a key (spec §2d)")
        name = rest[0]
        if not is_valid_agent_segment(name, valid_agents):
            return _undeclared(_bad_agent_reason(name, valid_agents))
        if name == "default":
            # 🛑 CORE OWNS THIS TIER, so CORE's table is the whole of its vocabulary —
            # the same reason ``meta.agent.<agent>.*`` is judged against
            # :data:`DECLARED_META_AGENT_LEAVES` above. ``agent.default.<leaf>`` is the
            # ALL-AGENTS fallback layer, and a plugin declares specifics for the agent it
            # ships, never for every other agent on the machine. Spec §0 says it outright:
            # *"the base system owns ONLY universal keys: agent.default.* + the generic
            # agent.<agent>.<key> contract SHAPE. Every non-universal specific … is
            # established AND modified by the PLUGIN"* — so a plugin's specific has no
            # slot HERE, only under its own agent. Unioning the plugin set in let goose's
            # ``provider`` classify as ``agent.default.provider``, which the ratified
            # manifest names not-a-key twice (``not_keys.code_residue``;
            # ``provider_disposition``, R-37) for want of any default-tier declaration,
            # and which §2d's Default-tier census does not enumerate.
            # ⚑ ``transform`` IS in the core table, so ``agent.default.transform`` stays
            # a key: this narrows to plugin-ONLY leaves, nothing else.
            # ⚑ ``leaves_known`` is left at its default because the CONCESSION was
            # already off here — ``_could_name_an_agent('default')`` is False — so this
            # changes the VOCABULARY and not the concession.
            # ⚑ It also asks NEITHER injected set, which strengthens the deferral rather
            # than re-arming it: even the refusal message now names core's table alone,
            # which at this tier is the honest list.
            return _agent_tail_reason(
                f"agent.{name}", rest[1:], DECLARED_AGENT_LEAVES,
            )
        return _agent_tail_reason(
            f"agent.{name}", rest[1:], leaves,
            # ⚑ THE CONCESSION IS ASKED IN THE RIGHT ORDER, and getting it backwards
            # un-armed §0 over a documented relic shape. The question is FIRST *could
            # this segment be an agent at all* (:func:`_could_name_an_agent`) and only
            # then *does this machine know its leaves*. A §2a category token fails the
            # first question, so it is never conceded: its vocabulary is the KEYSPACE's
            # own and is known on every machine. (``default`` no longer REACHES this
            # call — the branch above judges it against core's table, for that same
            # reason one step further — and the predicate still answers False for it.)
            # Ask only the second question and ``agent.common.plugins`` — the
            # undiscriminated relic MIGRATION.md §2.11 tells users to grep for —
            # classifies as a KEY, because no plugin declares an agent named ``common``.
            # ⚑ Both exclusions live HERE rather than in a supplier for the reason
            # :func:`is_valid_agent_segment` gives: their standing is the KEYSPACE's,
            # so every supplier gets it right by not having to know it.
            # ⚑ DEFERRED, not merely passed: ``name in agents_with_known_leaves`` is
            # the production supplier's plugin import, and evaluating it here would
            # charge every ``agent.<agent>.<core-leaf>`` path for it (see
            # :func:`_agent_tail_reason`). The thunk is pure, so WHEN it is asked
            # changes only the cost.
            leaves_known=lambda: (
                not _could_name_an_agent(name)
                or agents_with_known_leaves is None
                or name in agents_with_known_leaves
            ),
        )

    return _undeclared(
        f"'{head}' is not a declared namespace (declared: config, system, "
        f"agent, workset, box, meta, pref) — the keyspace is CLOSED (spec §0)"
    )


# ---------------------------------------------------------------------------
# The STORE-PATH classifier (spec §0)
# ---------------------------------------------------------------------------
#
# :func:`key_validity` answers "is this dotted STRING a key". A resolved STORE poses
# a second question the first one cannot: a path INTO a store may be a key, a VALUE
# address inside one, scaffolding the store needs, or plain data. The rules below
# answer THAT, and they live here — beside the validator they consult — because they
# now have THREE consumers: the pytest write census, the report-only resolve probe in
# ``settings_keyspace_probe``, and ``settings_launch._refuse_undeclared_snapshot``,
# which is the one that RAISES. A second carrier of one shape is the defect class this
# project keeps paying for; there is exactly one — which is why the third consumer
# arrived as a caller rather than as a mode of the probe.
#
# PURE, like the rest of this module: the declared-keyspace ORACLE is injected, so
# nothing here reaches for plugin discovery or an agent set.


#: The tokens a KEYSPACE path may start with: the four scopes (``kb_store``'s own
#: containment order), the three non-scope namespaces, and the reserved internal
#: node — included so a ``binding_derivations`` path is recognised as the node the
#: SPEC names (:data:`Verdict.RESERVED`) rather than dismissed as an unrooted
#: fragment whose true path the walker cannot know.
KEYSPACE_ROOTS: Final[frozenset[str]] = (
    frozenset(SCOPE_CONTAINMENT) | {"config", "meta", "pref", BINDING_DERIVATIONS_NODE}
)


class Verdict:
    """The class a store PATH lands in. :data:`FINDING_VERDICTS` are the FINDINGS.

    A resolved store legitimately holds a great deal that is not a key, and a
    classifier that flagged all of it would report noise. ⚑⚑ EVERY CLASS IS
    STRUCTURAL — decided by the path's SHAPE or by a constant the SPEC sanctions.
    There is no list of blessed key NAMES here, and none may be added: a name-keyed
    exemption is exactly the carve-out that hides the next finding behind it.

    ``DECLARED``     the oracle accepts the whole path. A key.
    ``VALUE``        a proper PREFIX is a declared key, so the rest addresses a VALUE
                     INSIDE it — ``box.caches``'s destinations, ``box.masks``'s
                     entries, a ``bindings`` arm's map. Structure, not a key.
    ``DATA_SEGMENT`` a segment CONTAINS A DOT, so the path cannot be a key path at
                     all (see :func:`render_store_path`).
    ``NAMESPACE``    the keyspace DECLARES this path as an interior — a scope table,
                     an agent tier, a ``meta`` group, an ``auth`` sub-table (see
                     :class:`KeyClass`). PROVISIONAL, exactly as ``UNDECLARED`` is: a
                     NODE here is store structure and :func:`container_notes` rescues
                     it to ``CONTAINER``; a SCALAR here is left alone and IS a
                     finding, because a namespace is not a place a value may sit.
    ``CONTAINER``    an intermediate NODE carrying declared keys underneath it
                     (``box.bindings``), or one the keyspace declares as a
                     ``NAMESPACE``. Scaffolding. Applied by
                     :func:`container_notes`, which needs the whole path SET.
    ``UNROOTED``     the root segment is not a keyspace root, so this is a
                     scope-LOCAL or fragment store whose key path cannot be known. A
                     fragment that reaches a real store is judged THERE, with its
                     true path, so nothing is lost by declining to guess.
    ``RESERVED``     the RESERVED INTERNAL NODE the spec names in so many words:
                     *"The derivation is NOT a key — it is a RESERVED INTERNAL NODE
                     … rides inside the per-launch snapshot as an internal node named
                     `binding_derivations`"* (spec §0, ABSTRACT declarations).
    ``UNDECLARED``   none of the above: something put a path into a store that the
                     keyspace does not declare.

    ⚑ A consumer may add classes of its OWN by subclassing — the pytest census adds
    ``NEGATIVE`` for a path the running test declared it would write. What it may not
    do is re-spell one of these.
    """
    DECLARED = "DECLARED"
    VALUE = "VALUE"
    DATA_SEGMENT = "DATA_SEGMENT"
    NAMESPACE = "NAMESPACE"
    CONTAINER = "CONTAINER"
    UNROOTED = "UNROOTED"
    RESERVED = "RESERVED"
    UNDECLARED = "UNDECLARED"


#: The verdicts that are STILL a finding once :func:`container_notes` has run.
#: ⚑ ONE carrier, because the alternative is a consumer that filters on
#: ``UNDECLARED`` alone and so reports a SCALAR-at-a-namespace as clean — a
#: widening that fails SILENTLY, by going green.
FINDING_VERDICTS: Final[frozenset[str]] = frozenset({
    Verdict.UNDECLARED, Verdict.NAMESPACE,
})


#: Why :data:`Verdict.RESERVED` is not an exemption. Sourced from the declaring
#: constant so a rename cannot leave a stale spelling behind.
RESERVED_NODE_REASON: Final[str] = (
    f"{BINDING_DERIVATIONS_NODE!r} is the RESERVED INTERNAL NODE the spec names in "
    f"so many words (§0, ABSTRACT declarations): the materialised binding an abstract "
    f"declaration derives is machinery output, not a settable surface. Its interior "
    f"is declaration keys and box DESTINATIONS, which are data."
)


class Judgement(NamedTuple):
    """One path's class, the declared key it sits in, & where the DATA starts."""
    verdict: str
    key: str
    key_len: int  # how many leading segments are key path; the rest is DATA
    note: str


class StoreNode(NamedTuple):
    """One judged path as :func:`container_notes` needs to see it."""
    verdict: str
    is_node: bool


def render_store_path(segments: Collection[str], key_len: int | None = None) -> str:
    """A display path that NEVER renders non-key data as a dotted key.

    ⚑⚑ A CORRECTNESS job, not a cosmetic one. A destination is DATA and never
    appears in a dotted key, so the *key_len* leading segments are dot-joined and
    everything after them is PIPE-joined inside ``⟨⟩`` — visibly not key path. With
    no *key_len* the whole path is key path, and even then a segment carrying a dot
    forces the pipe form rather than forging a segment boundary that is not there.
    """
    parts = list(segments)
    if key_len is None or key_len >= len(parts):
        return " | ".join(parts) if any("." in s for s in parts) else ".".join(parts)
    head = ".".join(parts[:key_len])
    tail = " | ".join(parts[key_len:])
    return f"{head} ⟨{tail}⟩" if head else f"⟨{tail}⟩"


def classify_store_path(
    segments: tuple[str, ...], *, oracle: Callable[[str], KeyJudgement],
) -> Judgement:
    """One path's :class:`Judgement`, ignoring what landed UNDER it.

    *oracle* answers :func:`key_class`'s question — KEY, NAMESPACE or UNDECLARED.
    :func:`key_class` is the production answer; it is injected rather than called so
    this stays pure and so a caller can memoise (the prefix walk asks about every
    proper prefix, and prefixes repeat heavily across a store).

    ⚑ THE ORACLE MUST ANSWER ALL THREE. With a key-or-not oracle this function
    cannot tell a declared interior from a fabrication, and the only distinguisher
    left is DEPTH — which is what it used, rescuing a namespace at depth 1 and
    reporting ``meta.box.agent`` / ``agent.<agent>`` / ``meta.box.agent.auth`` as
    violations whenever their last child happened to be dropped.

    The CONTAINER rule is NOT applied here: it needs what landed underneath a node
    and whether this path IS one, neither of which a single path shows. See
    :func:`container_notes`.
    """
    if not segments:
        return Judgement(Verdict.UNROOTED, "", 0, "empty path")
    if segments[0] == BINDING_DERIVATIONS_NODE:
        return Judgement(
            Verdict.RESERVED, BINDING_DERIVATIONS_NODE, 1, RESERVED_NODE_REASON,
        )
    if segments[0] not in KEYSPACE_ROOTS:
        return Judgement(
            Verdict.UNROOTED, "", len(segments),
            f"{segments[0]!r} is not a keyspace root: a scope-LOCAL or fragment "
            f"store, whose key path this cannot know",
        )
    for cut in range(1, len(segments) + 1):
        if "." in segments[cut - 1]:
            # ⚑ STOP. A dotted segment is DATA; asking the oracle past it would forge
            # a key out of a destination (or an env VAR name — the open question
            # ``ENV_KEY_RE`` forbids and the persona path never checks).
            return Judgement(
                Verdict.DATA_SEGMENT, ".".join(segments[:cut - 1]), cut - 1,
                f"segment {segments[cut - 1]!r} contains a dot, so this is not a "
                f"key path",
            )
        prefix = ".".join(segments[:cut])
        if oracle(prefix).cls is KeyClass.KEY:
            if cut == len(segments):
                return Judgement(Verdict.DECLARED, prefix, cut, "")
            return Judgement(
                Verdict.VALUE, prefix, cut,
                f"a value address inside the declared key {prefix!r}",
            )
    full = ".".join(segments)
    judgement = oracle(full)
    verdict = (
        Verdict.NAMESPACE if judgement.cls is KeyClass.NAMESPACE
        else Verdict.UNDECLARED
    )
    return Judgement(verdict, "", len(segments), judgement.reason)


def container_notes(
    nodes: Mapping[tuple[str, ...], StoreNode],
) -> dict[tuple[str, ...], str]:
    """The paths :data:`Verdict.CONTAINER` rescues, each mapped to its NOTE.

    *nodes* is the WHOLE judged set — the rule is about relationships between paths,
    so a partial view gives a wrong answer. Every returned path is re-classed to
    ``CONTAINER`` by the caller; the value is which of the two rules applied.

    TWO RULES, and the ``is_node`` guard is read HERE and nowhere else — a namespace
    is a NODE, so a SCALAR at one of these paths is an undeclared SHAPE and keeps
    reddening under both.

    ⚑ A DECLARED ``NAMESPACE`` is rescued unconditionally, because its key-hood is
    the SPEC's and cannot depend on what a given session happened to write beneath
    it. An empty ``box: {}`` scope table in a settings file is a scope table, not a
    fabrication; so is a ``meta.box.agent`` whose only child was dropped by §6b when
    its @-ref referent was absent. ⚑⚑ THIS REPLACES A DEPTH TEST. The rule used to
    read ``len(segments) == 1``, which is a POSITIONAL PROXY for namespace-hood: it
    rescued ``meta`` and reported ``meta.box.agent``, though the spec calls both a
    namespace one sentence apart (:42, §2b). Ask the keyspace, do not count segments.

    ⚑ AN ``UNDECLARED`` INTERMEDIATE node is judged by WHAT LANDED UNDER IT rather
    than by a list: a node with nothing declared beneath it is not scaffolding, so an
    empty fabricated subtree stays a violation. That is why this is a filter and not
    a blanket "nodes are exempt".
    """
    real = {Verdict.DECLARED, Verdict.VALUE}
    carriers: set[tuple[str, ...]] = set()
    for segments, node in nodes.items():
        if node.verdict in real:
            for cut in range(1, len(segments)):
                carriers.add(segments[:cut])
    rescued: dict[tuple[str, ...], str] = {}
    for segments, node in nodes.items():
        if not node.is_node:
            continue
        if node.verdict == Verdict.NAMESPACE:
            rescued[segments] = (
                "a node at a path the keyspace declares as a NAMESPACE (spec §0)"
            )
        elif node.verdict == Verdict.UNDECLARED and segments in carriers:
            rescued[segments] = (
                "an intermediate node carrying declared keys underneath it"
            )
    return rescued


#: Cap on :func:`walk_store_paths` recursion; a self-referential store would
#: otherwise not terminate.
MAX_STORE_DEPTH: Final[int] = 64


def walk_store_paths(
    node: KeyStore[Any], prefix: tuple[str, ...] = (),
) -> Iterator[tuple[tuple[str, ...], bool]]:
    """Every path in *node*, depth-first: its SEGMENTS and whether it is a NODE.

    Segments rather than a dotted string, because a dest-keyed segment is routinely
    a filesystem path with dots in it and a dotted string loses the very segment
    boundaries :func:`classify_store_path` turns on.

    ⚑ UNBOUND ``dict.items`` (S3): a resolved snapshot is exactly where a
    user-named leaf lives, and one spelled ``items`` would shadow the bound method
    into a crash.
    """
    if len(prefix) >= MAX_STORE_DEPTH:
        return
    for key, value in dict.items(node):
        segments = prefix + (key,)
        is_node = isinstance(value, KeyStore)
        yield segments, is_node
        if is_node:
            yield from walk_store_paths(value, segments)


def undeclared_store_paths(
    store: KeyStore[Any], *, oracle: Callable[[str], KeyJudgement],
) -> list[tuple[tuple[str, ...], Judgement]]:
    """Every path in *store* the CLOSED keyspace does not declare (spec §0).

    The whole pipeline in one call: walk, classify each path, then apply the
    CONTAINER rule over the complete set. Returns ``(segments, judgement)`` pairs
    sorted by path — the SEGMENTS travel with the judgement because a
    :class:`Judgement` alone cannot be rendered (an ``UNDECLARED`` one names no key,
    which is the point of it).

    ⚑ It REPORTS; refusing is the CALLER's decision, and the two live callers take
    it oppositely off one list. ``settings_keyspace_probe.observe`` writes a row and
    returns; ``settings_launch._refuse_undeclared_snapshot`` raises naming every
    entry. Keeping the verdict here and the policy there is what let the refusal be
    measured before it was armed.
    """
    judged: dict[tuple[str, ...], Judgement] = {}
    nodes: dict[tuple[str, ...], StoreNode] = {}
    for segments, is_node in walk_store_paths(store):
        judgement = classify_store_path(segments, oracle=oracle)
        judged[segments] = judgement
        nodes[segments] = StoreNode(judgement.verdict, is_node)
    rescued = container_notes(nodes)
    return [
        (segments, judgement) for segments, judgement in sorted(judged.items())
        if judgement.verdict in FINDING_VERDICTS and segments not in rescued
    ]
