"""The CLOSED KEYSPACE — what IS a key, and the one validator that answers it.

Spec §0: *"The keyspace is CLOSED — an undeclared key is NOT a key.
Every legal key is either enumerated in this spec or generated by one of its
declared PARAMETRIC families … Anything outside it is REJECTED: reading,
setting, or resolving an undeclared key is an ERROR that NAMES the offending
key."* This module is the code-side DECLARATION of that set and the single
predicate over it, :func:`key_validity`.

What this module answers, and what it does NOT
----------------------------------------------
This module answers **"is this a key at all?"**
``config_keys._KEY_ROUTES`` / ``KNOWN_CONFIG_KEYS`` answer a DIFFERENT
question — **"where does a ``config set`` of this key land, and is it reachable
from the CLI?"**. The two lists are therefore NOT duplicates and must not be
collapsed: the settable surface is a SUBSET of the keyspace (``run_args`` and
``transform_settings`` are real keys with no CLI route; ``meta.*`` keys are real
keys that are never settable at all). :func:`~kanibako.settings.settings_keyspace`'s set
is the superset, and ``tests/test_settings_keyspace.py`` asserts that direction
so the two cannot silently diverge.

⚑ WHAT IS DECLARED HERE IS THE **SPEC's** KEY SET, NOT THE CODE's
------------------------------------------------------------------
A key the spec declares is valid here even when no consumer reads it yet
(``system.agent`` until P7 wires agent selection; ``agent.<a>.canon`` until the
canon-books phase). §0's closed keyspace is about DECLARATION; an unread key is
not an undeclared one. The alternative — gating each key on its implementing
phase — makes this module a moving target and reintroduces exactly the "which
list is authoritative" question §0 exists to settle.

Coverage boundary — AUTHORITATIVE vs SUPPORTING (read before relying on this)
-----------------------------------------------------------------------------
* **AUTHORITATIVE (complete, test-pinned):** the ``pref.*`` allowlist surface —
  ``system.agent`` and every ``agent.<agent>.**`` form (§2h). ``settings_prefs``
  filter 1 depends on this being exact, and it is.
* **SUPPORTING (best-effort):** every other scope. These entries exist so an
  error MESSAGE can be accurate ("``box.image`` is a real key, it is just not
  requestable") rather than misleading. A gap here can only degrade a message,
  never an outcome: under §2h any target outside the allowlist is refused by the
  allowlist filter regardless of what this module says about it.

That boundary is also why this module is NOT yet wired into ``config get`` or
into the assemble/launch path. Those two consumers turn an undeclared key into a
user-visible failure (a launch that refuses to start), which is a change with a
blast radius of every stored legacy key — tracked as the "closed-keyspace
resolve enforcement" follow-on, gated on :data:`RETIRING_KEYS` being empty.

PURE. No I/O, no plugin import at module load. The set of valid AGENT names is
an injected parameter (``valid_agents``) precisely so this module stays pure and
testable; ``settings_prefs.default_valid_agents`` is the one production supplier.
"""

from __future__ import annotations

import re
from typing import Collection, Final

from kanibako.settings.settings_store import _RESERVED_KEY_NAMES as _STORE_RESERVED

# ---------------------------------------------------------------------------
# The keyspace version stamp
# ---------------------------------------------------------------------------

#: The declared keyspace VERSION — one leg of the three-way stamp (the spec
#: header · the manifest's ``registry.keyspace`` field · this constant),
#: flipped to ``"1.8.0"`` in-tree before the prod promote per
#: Part-4-as-amended. Imported by nothing yet — C2's CI stamp assertion is
#: its first consumer.
KEYSPACE_VERSION: Final[str] = "1.8.0rc"

# ---------------------------------------------------------------------------
# Layer 1 — config.* (spec §1)
# ---------------------------------------------------------------------------

#: The Layer-1 bootstrap CONFIG keys (spec §1). Human-edited in
#: ``kanibako_config.yaml``; never CLI-settable (block B2) but unquestionably KEYS.
DECLARED_CONFIG_LEAVES: Final[frozenset[str]] = frozenset({
    "data", "settings", "agents", "primary_workset", "registry", "journal",
})

# ---------------------------------------------------------------------------
# Layer 2 — the scope SCALAR leaves (spec §2b / §2c / §2e / §2g)
# ---------------------------------------------------------------------------

#: ``system.<leaf>`` (spec §2g). ⚑ ``system.agent`` is the SPEC name
#: (D-M2 superseded 2026-07-29) and, since P7, the ONLY spelling: the stored
#: ``system.default_agent`` is RETIRED and REFUSED by name at assembly
#: (``settings_assemble.RETIRED_FILE_KEYS``).
DECLARED_SYSTEM_LEAVES: Final[frozenset[str]] = frozenset({
    "channelroot", "template", "canon", "backup", "cache", "runtime",
    "agent", "setup_completed",
})

#: ``system.channels.<leaf>`` (spec §2g).
DECLARED_SYSTEM_CHANNEL_LEAVES: Final[frozenset[str]] = frozenset({
    "common", "chat", "broadcast", "mailboxes", "share",
})

#: ``system.auth.<leaf>`` — the auth 3-tier gate (spec §2g/§2c; settable ONLY
#: from the system floor per §0).
DECLARED_SYSTEM_AUTH_LEAVES: Final[frozenset[str]] = frozenset({"share_allowed"})

#: ``box.<leaf>`` (spec §2b). ⚑ ``box.agent_name`` is RETIRED (§2b
#: ) and is deliberately ABSENT — its replacement is ``pref.system.agent``.
DECLARED_BOX_LEAVES: Final[frozenset[str]] = frozenset({
    "image", "share_images", "images_store", "canon", "shell", "enable_vault",
})

#: ``box.auth.<leaf>`` (spec §2b).
DECLARED_BOX_AUTH_LEAVES: Final[frozenset[str]] = frozenset({
    "global_enabled", "workset_enabled",
})

#: ``workset.<leaf>`` (spec §2c ALL WORKSETS, ALL PROJECTS,
#: STANDALONE, §2e).
DECLARED_WORKSET_LEAVES: Final[frozenset[str]] = frozenset({
    "workspaces", "boxes", "logs", "registry", "template", "canon",
    "kuid", "skip_kuid_check", "vault_ro", "vault_rw", "channelroot",
})

#: ``workset.auth.<leaf>`` (spec §2c).
DECLARED_WORKSET_AUTH_LEAVES: Final[frozenset[str]] = frozenset({
    "share_allowed", "global_sync", "path",
})

#: ``workset.channels.<leaf>`` (spec §2c). TWO sub-families make up the set:
#: the workset-LOCAL type roots (``common``/``chat``/``broadcast``/``share`` —
#: primary+named only, rooted at ``@workset.channelroot``) and the ALL-PROJECTS
#: per-workset ADDRESSES into the SYSTEM stores (``mailboxes``/``share_global``
#: — ``@system.channels.{mailboxes,share}/@meta.workset.name``, present in
#: EVERY mode, keyed ``__PRIMARY__`` | ``<named>`` | ``__STANDALONE__``).
#: Mailboxes still AGGREGATE at system only (§2f) — the workset leaf is the
#: workset's declared ADDRESS into that aggregate, not a second aggregate,
#: which is why the earlier "a workset has no mailboxes" exclusion here was a
#: mis-read (R-35, RATIFIED: fix the CODE): ``meta.box.inbox`` /
#: ``meta.box.share_global`` derive through these keys in the spec's formulas.
#: This set must EQUAL ``settings_launch._WORKSET_CHANNEL_LEAVES`` (the launch
#: floor's allowlist) — a test pins the agreement.
DECLARED_WORKSET_CHANNEL_LEAVES: Final[frozenset[str]] = frozenset({
    "common", "chat", "broadcast", "share", "mailboxes", "share_global",
})

#: ``agent.<agent>.<leaf>`` — the generic per-agent contract (spec §2d).
#: Every one of these ALSO exists as ``agent.default.<leaf>`` (the agent tier's
#: fallback layer, §2).
#:
#: ⚑ This is the AUTHORITATIVE list — ``settings_prefs`` filter 1 rejects on it,
#: so an omission here is a user-visible refusal of a legal request. Each entry
#: carries its §2d line. It is UNIONED at call time with the plugin-declared
#: ``setting_descriptors()`` keys (§0 "Agent specifics are
#: PLUGIN-declared"), which is why ``endpoint`` appearing here is a floor, not a
#: ceiling.
DECLARED_AGENT_LEAVES: Final[frozenset[str]] = frozenset({
    "access",              # §2d (the permission TIER — SUPERSEDES ``auto_approve``)
    "allow_helpers",       # §2d
    "continue_mode",       # §2d
    "bootstrap",           # §2d
    "model",               # §2d
    "run_args",            # §2d
    "transform_settings",  # §2d
    "endpoint",            # §2d (claude-declared; part of the generic shape)
    "template",            # §2d
    "canon",               # §2d
})

# ---------------------------------------------------------------------------
# The ``access`` permission TIER — the one enum-valued agent leaf (spec §2d)
# ---------------------------------------------------------------------------

#: The LEGAL values of ``agent.<agent>.access`` / ``agent.default.access``
#: (spec §2d, R-41), ordered LEAST → MOST permissive:
#:
#: * ``restricted`` — everything prompts.
#: * ``editing`` — the middle tier: free for safe, contained edit-class
#:   operations; ask at the boundaries.
#: * ``full`` — today's bypass (the DEFAULT: the box IS the containment
#:   boundary, so in-box permission prompts are a second fence inside the first).
#:
#: ⚑ The value set is CLOSED (spec §0): an unknown value is REJECTED LOUDLY at
#: BOTH ends — ``config set`` time (``config_keys.access_value_error``) and
#: launch (``targets.assembly.effective_access``). It is NEVER treated as
#: permissive: a typo must not be the difference between prompting and not.
#: Declared HERE, beside the leaf itself, so the settable surface, the launch
#: resolver and the plugin descriptors all read ONE list.
ACCESS_TIERS: Final[tuple[str, ...]] = ("restricted", "editing", "full")

#: The tier a launch uses when NO scope in the cascade sets ``access``
#: (spec §2d ``agent.default.access | full``; R-41 CLOSED: option (a), today's
#: behaviour preserved).
ACCESS_DEFAULT: Final[str] = "full"

# ---------------------------------------------------------------------------
# The §2a CATEGORIES — parametric over every scope
# ---------------------------------------------------------------------------

#: The bind-shaped categories: ``<scope>.<category>.<name>``, ``<name>`` FREE.
#: ⚑ The free ``<name>`` IS the "VALIDITY, not EXISTENCE" clause (§2h):
#: a NEW name inside a parametric family is exactly what a user may add.
BIND_CATEGORIES: Final[frozenset[str]] = frozenset({
    "bindings.ro", "bindings.rw", "caches", "seeded", "common", "synced",
})

# (There is deliberately no CATEGORY_SCOPES constant. The scope dispatch in
# :func:`key_validity` is an explicit if-chain on the head token, and the
# category test runs on the TAIL via :func:`_looks_like_category`, so a set of
# "scopes that may carry a category" has no consumer. It existed briefly and was
# DELETED rather than kept as an unused declaration — an unwired constant reads
# as a contract something is supposed to honour.)

# ---------------------------------------------------------------------------
# meta.* — the RO families (spec §0, §2c, §2d)
# ---------------------------------------------------------------------------

DECLARED_META_RUNTIME_LEAVES: Final[frozenset[str]] = frozenset({
    "ws_root", "ws_name", "project_type",
})
DECLARED_META_WORKSET_LEAVES: Final[frozenset[str]] = frozenset({
    "path", "name", "settings",
})
DECLARED_META_BOX_LEAVES: Final[frozenset[str]] = frozenset({
    "path", "name", "mode", "workspace", "settings",
    "inbox", "share_global", "share_workset",
})
DECLARED_META_BOX_AUTH_LEAVES: Final[frozenset[str]] = frozenset({"workset_path"})
DECLARED_META_AGENT_LEAVES: Final[frozenset[str]] = frozenset({
    "name", "path", "settings", "mode", "exec",
})
DECLARED_META_AGENT_AUTH_LEAVES: Final[frozenset[str]] = frozenset({"share_support"})

# ---------------------------------------------------------------------------
# Reserved leaf names (spec §0)
# ---------------------------------------------------------------------------

#: Public ``dict`` method names a leaf key may NOT be called — a collision-safety
#: floor on the resolved data structure (spec §0). Matched
#: CASE-SENSITIVELY.
RESERVED_LEAF_NAMES: Final[frozenset[str]] = frozenset({
    "get", "keys", "values", "items", "pop", "popitem", "setdefault",
    "update", "clear", "copy", "fromkeys",
})

# ⚑ Drift guard: this list must be the SAME set the KeyStore rejects at write
# time. Two copies of a collision-safety floor that disagree is worse than one —
# a name accepted here and rejected there fails deep in the store with no
# reference to the key the user wrote.
assert RESERVED_LEAF_NAMES == _STORE_RESERVED, (
    "settings_keyspace.RESERVED_LEAF_NAMES has drifted from "
    "settings_store._RESERVED_KEY_NAMES"
)

_DUNDER_RE: Final = re.compile(r"^__.*__$")

#: ``env.<VAR>`` / ``secret_path.<VAR>`` variable-name shape (spec §2a; mirrors
#: ``settings_categories.SECRET_VAR_RE`` — kept as its own compiled copy so this
#: module imports nothing from the settings stack).
_VAR_RE: Final = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# ---------------------------------------------------------------------------
# Keys the ARC is mid-retiring (the conformance-test exemptions)
# ---------------------------------------------------------------------------

#: Spellings still present in ``config_keys.KNOWN_CONFIG_KEYS`` that the
#: SPEC has already retired or renamed. Each names the phase that deletes it.
#: ``tests/test_settings_keyspace.py`` exempts exactly these and nothing else —
#: **a SECOND entry means the spec and the settable surface disagree somewhere
#: this arc has not accounted for, and that is a STOP-and-report condition, not
#: an exemption to add.**  (It held THREE until P7 retired ``box.agent_name`` and
#: ``system.default_agent``; the cap shrinks with the set, deliberately.)
#:
#: The "closed-keyspace resolve enforcement" follow-on is gated on this set
#: being EMPTY (plus: the conformance test green with no exemptions, and a
#: real-store sweep per migration-issues M-1/M-2).
#: ⚑ NOW **EMPTY** (C-CANON seeds half, 2026-08-01): M-11 renamed
#: ``system.base_template`` → ``system.template`` and dropped the old spelling from
#: ``KNOWN_CONFIG_KEYS``, so the spec and the settable surface agree with no
#: exemptions. An entry appearing here again means a NEW divergence, which is a
#: STOP-and-report condition, not a line to add.
RETIRING_KEYS: Final[frozenset[str]] = frozenset()


# ---------------------------------------------------------------------------
# The validator
# ---------------------------------------------------------------------------

def leaf_name_reason(leaf: str) -> str | None:
    """Reject a RESERVED / dunder leaf name (spec §0).

    PUBLIC because the floor is due at TWO moments, not one: spec §0 says a
    reserved name is "rejected loudly at write/``config set`` time", so the
    ``<scope>.env.<VAR>`` set/reset route calls this directly
    (``config_keys.scope_env_var_error``) rather than waiting for the
    resolve-time :func:`key_validity` pass — a stored key that only fails at the
    NEXT launch is exactly the deferred surprise §0 forbids.
    """
    if leaf in RESERVED_LEAF_NAMES:
        return (
            f"'{leaf}' is a RESERVED key name (a public dict method) and may not "
            f"name a key (spec §0 reserved key names)"
        )
    if _DUNDER_RE.match(leaf):
        return (
            f"'{leaf}' matches the dunder pattern and may not name a key "
            f"(spec §0 reserved key names)"
        )
    return None


def is_valid_agent_segment(segment: str, valid_agents: Collection[str]) -> bool:
    """Is *segment* a legal ``agent.<HERE>`` discriminator?

    ``default`` (the agent tier's all-agents FALLBACK, §2) or a member
    of *valid_agents*. The caller decides what "valid agent" means — see
    ``settings_prefs.default_valid_agents``, which answers it as "a discovered
    harness, or a persona node whose harness is discovered" (§2h: the
    test is *is it a VALID agent*, NOT *is it the ACTIVE agent*).
    """
    return segment == "default" or segment in valid_agents


def _category_reason(
    prefix: str, rest: list[str], *, what: str
) -> str | None:
    """Validate a ``<category>.<name>`` tail under an already-valid *prefix*.

    *rest* is the tail AFTER the scope token(s). Returns ``None`` when the tail
    names a declared §2a category entry, else a reason. *what* names the scope
    for the message ("the box scope", "agent 'claude'", …).
    """
    if not rest:
        return f"'{prefix}' names {what} itself, which is not a key"
    head = rest[0]

    # masks — the value-less keyed category (spec §2a). The KEY is exactly
    # ``<scope>.masks``; entries live INSIDE it as a dict[box_dest -> bool|None],
    # and a box_dest is a PATH, not a key segment, so a dotted tail under masks is
    # a value address rather than a key. Accept the bare form only.
    if head == "masks":
        if len(rest) == 1:
            return None
        return (
            f"'{prefix}.masks.{'.'.join(rest[1:])}' is not a key: masks is a "
            f"keyed category whose entries are box destinations inside the "
            f"'{prefix}.masks' value, not key segments (spec §2a)"
        )

    # env.<VAR> / secret_path.<VAR> — scalar-valued, VAR-keyed (spec §2a).
    if head in ("env", "secret_path"):
        if len(rest) != 2:
            return (
                f"'{prefix}.{'.'.join(rest)}' is not a key: {head} is keyed per "
                f"variable — '{prefix}.{head}.<VAR>' (spec §2a)"
            )
        var = rest[1]
        if not _VAR_RE.match(var):
            return (
                f"'{var}' is not a legal environment variable name for "
                f"'{prefix}.{head}.<VAR>' (spec §2a)"
            )
        return leaf_name_reason(var)

    # bindings.{ro,rw}.<name> — the arm is REQUIRED (spec §2d: an
    # ARM-LESS binding is not a declared key).
    if head == "bindings":
        if len(rest) < 3 or rest[1] not in ("ro", "rw"):
            return (
                f"'{prefix}.{'.'.join(rest)}' is not a key: bindings are declared "
                f"per ARM — '{prefix}.bindings.ro.<name>' / "
                f"'{prefix}.bindings.rw.<name>' (spec §2a / §2d L960-964)"
            )
        return leaf_name_reason(rest[-1])

    # The remaining leaf categories: caches / seeded / common / synced.
    if head in {c for c in BIND_CATEGORIES if "." not in c}:
        if len(rest) < 2:
            return (
                f"'{prefix}.{head}' is a CATEGORY ROOT, not a key; entries are "
                f"named — '{prefix}.{head}.<name>' (spec §2a)"
            )
        return leaf_name_reason(rest[-1])

    return None  # signals "not a category tail" — the caller reports the leaf.


def _looks_like_category(rest: list[str]) -> bool:
    """Does *rest* start with a §2a category token?"""
    if not rest:
        return False
    head = rest[0]
    # ``bindings`` is the ARM ROOT for ``bindings.{ro,rw}``; the value-less and
    # scalar-valued categories are named beside the bind-shaped ones.
    return (
        head == "bindings"
        or head in {c for c in BIND_CATEGORIES if "." not in c}
        or head in ("masks", "env", "secret_path")
    )


def _scope_reason(
    scope: str,
    rest: list[str],
    *,
    leaves: frozenset[str],
    sub_tables: dict[str, frozenset[str]],
    what: str,
) -> str | None:
    """Validate a NON-agent scope key ``<scope>.<rest…>``."""
    if _looks_like_category(rest):
        return _category_reason(scope, rest, what=what)
    if len(rest) == 1:
        if rest[0] in leaves:
            return leaf_name_reason(rest[0])
        return (
            f"'{rest[0]}' is not a declared {what} key (declared: "
            f"{', '.join(sorted(leaves))}, plus the §2a categories)"
        )
    if len(rest) == 2 and rest[0] in sub_tables:
        table = sub_tables[rest[0]]
        if rest[1] in table:
            return leaf_name_reason(rest[1])
        return (
            f"'{scope}.{rest[0]}.{rest[1]}' is not a declared key (declared "
            f"'{scope}.{rest[0]}.*': {', '.join(sorted(table))})"
        )
    return (
        f"'{scope}.{'.'.join(rest)}' is not a declared {what} key "
        f"(spec §0 — the keyspace is CLOSED)"
    )


def _meta_reason(
    rest: list[str],
    valid_agents: Collection[str],
    leaves: Collection[str] = DECLARED_AGENT_LEAVES,
) -> str | None:
    """Validate a ``meta.<rest…>`` key (spec §0, §2c, §2d)."""
    if not rest:
        return "'meta' is a namespace, not a key"
    group = rest[0]
    tail = rest[1:]

    if group == "runtime":
        if tail and len(tail) == 1 and tail[0] in DECLARED_META_RUNTIME_LEAVES:
            return None
        return (
            f"'meta.runtime.{'.'.join(tail)}' is not a declared key (declared: "
            f"{', '.join(sorted(DECLARED_META_RUNTIME_LEAVES))})"
        )

    if group == "workset":
        if len(tail) == 1 and tail[0] in DECLARED_META_WORKSET_LEAVES:
            return None
        return (
            f"'meta.workset.{'.'.join(tail)}' is not a declared key (declared: "
            f"{', '.join(sorted(DECLARED_META_WORKSET_LEAVES))})"
        )

    if group == "box":
        if len(tail) == 1 and tail[0] in DECLARED_META_BOX_LEAVES:
            return None
        if len(tail) == 2 and tail[0] == "auth":
            if tail[1] in DECLARED_META_BOX_AUTH_LEAVES:
                return None
            return (
                f"'meta.box.auth.{tail[1]}' is not a declared key (declared: "
                f"{', '.join(sorted(DECLARED_META_BOX_AUTH_LEAVES))})"
            )
        if tail and tail[0] == "agent":
            # meta.box.agent.<key> — the RO MIRROR of the effective agent
            # subtree (spec §2b). It mirrors the WHOLE subtree, so its tail
            # is any valid agent-scope tail.
            return _agent_tail_reason("meta.box.agent", tail[1:], leaves)
        return (
            f"'meta.box.{'.'.join(tail)}' is not a declared key (declared: "
            f"{', '.join(sorted(DECLARED_META_BOX_LEAVES))}, auth.workset_path, "
            f"and the agent.* read-back mirror)"
        )

    if group == "agent":
        if not tail:
            return "'meta.agent' is a namespace, not a key (spec §2d)"
        name = tail[0]
        if not is_valid_agent_segment(name, valid_agents):
            return _bad_agent_reason(name, valid_agents)
        sub = tail[1:]
        if len(sub) == 1 and sub[0] in DECLARED_META_AGENT_LEAVES:
            return None
        if len(sub) == 2 and sub[0] == "auth":
            if sub[1] in DECLARED_META_AGENT_AUTH_LEAVES:
                return None
            return (
                f"'meta.agent.{name}.auth.{sub[1]}' is not a declared key "
                f"(declared: {', '.join(sorted(DECLARED_META_AGENT_AUTH_LEAVES))})"
            )
        return (
            f"'meta.agent.{name}.{'.'.join(sub)}' is not a declared key "
            f"(declared: {', '.join(sorted(DECLARED_META_AGENT_LEAVES))}, "
            f"auth.share_support)"
        )

    return (
        f"'meta.{group}' is not a declared meta group (declared: runtime, "
        f"workset, box, agent)"
    )


def _bad_agent_reason(name: str, valid_agents: Collection[str]) -> str:
    known = ", ".join(sorted({*valid_agents, "default"})) or "default"
    return (
        f"'{name}' is not a valid agent (valid: {known}). The agent segment of "
        f"an agent-scope key must name a real agent or the 'default' fallback "
        f"tier (spec §2d / §0 L21 — a bare 'agent.<key>' is not a key)"
    )


def _agent_tail_reason(
    prefix: str, tail: list[str], leaves: Collection[str] = DECLARED_AGENT_LEAVES,
) -> str | None:
    """Validate the tail of an agent-scope key, after the discriminator.

    *leaves* is the effective agent-leaf set: the core §2d contract UNIONED with
    what the PLUGINS declare (§0 — *"Agent specifics are PLUGIN-declared
    … Every non-universal specific is established AND modified by the PLUGIN,
    never hardcoded in core"*). Without the union a real plugin key is refused:
    goose declares ``provider`` through ``setting_descriptors()`` and it is a
    legitimate ``agent.goose.provider``.
    """
    if not tail:
        return f"'{prefix}' names an agent tier, not a key (spec §2d)"
    if _looks_like_category(tail):
        return _category_reason(prefix, tail, what=f"'{prefix}'")
    if len(tail) == 1:
        if tail[0] in leaves:
            return leaf_name_reason(tail[0])
        return (
            f"'{tail[0]}' is not a declared agent key (declared: "
            f"{', '.join(sorted(leaves))}, plus the §2a "
            f"categories) (spec §0 — the keyspace is CLOSED)"
        )
    return (
        f"'{prefix}.{'.'.join(tail)}' is not a declared agent key "
        f"(spec §0 — the keyspace is CLOSED)"
    )


def key_validity(
    key: str,
    *,
    valid_agents: Collection[str],
    agent_leaves: "Collection[str] | None" = None,
) -> str | None:
    """``None`` when *key* is a legal key under §0; else a REASON naming why not.

    A REASON string rather than a bool because every consumer must be able to
    tell the user WHY (spec §2h: *"the error NAMES which key, at which
    level, and WHY"*, and §0: an undeclared key errors NAMING the key).

    *valid_agents* is injected (purity) — the set of agent discriminators that
    are real, exclusive of ``"default"`` which is always legal. *agent_leaves*
    likewise injects the PLUGIN-declared agent keys to union over the core §2d
    set (``None`` = core only); see :func:`_agent_tail_reason`.

    The dispatch is on the FIRST segment; every branch reports against the
    spec section that declares the family.
    """
    if not key or not isinstance(key, str):
        return "the empty string is not a key"
    parts = key.split(".")
    if any(seg == "" for seg in parts):
        return (
            f"'{key}' has an empty path segment; a key is dot-separated "
            f"non-empty segments (spec §0)"
        )
    head, rest = parts[0], parts[1:]
    leaves = DECLARED_AGENT_LEAVES if agent_leaves is None else (
        frozenset(DECLARED_AGENT_LEAVES) | frozenset(agent_leaves)
    )

    if head == "config":
        if len(rest) == 1 and rest[0] in DECLARED_CONFIG_LEAVES:
            return None
        return (
            f"'{key}' is not a declared Layer-1 config key (declared: "
            f"{', '.join('config.' + k for k in sorted(DECLARED_CONFIG_LEAVES))})"
        )

    if head == "meta":
        return _meta_reason(rest, valid_agents, leaves)

    if head == "pref":
        # pref.<target-key> (spec §2h). The family is valid iff the TARGET is a
        # valid key. Whether it may be REQUESTED is a separate question the
        # allowlist + forbidden tiers answer (settings_prefs) — this is only
        # "is it a key".
        if not rest:
            return "'pref' is a namespace, not a key (spec §2h)"
        if rest[0] == "pref":
            return (
                "'pref.pref.…' is not a key: a request-of-a-request has no "
                "termination argument (spec §2h categorical tier)"
            )
        inner = key_validity(
            ".".join(rest), valid_agents=valid_agents, agent_leaves=agent_leaves,
        )
        if inner is None:
            return None
        return f"its target is not a declared key — {inner}"

    if head == "system":
        return _scope_reason(
            "system", rest,
            leaves=DECLARED_SYSTEM_LEAVES,
            sub_tables={
                "channels": DECLARED_SYSTEM_CHANNEL_LEAVES,
                "auth": DECLARED_SYSTEM_AUTH_LEAVES,
            },
            what="system",
        )

    if head == "workset":
        return _scope_reason(
            "workset", rest,
            leaves=DECLARED_WORKSET_LEAVES,
            sub_tables={
                "channels": DECLARED_WORKSET_CHANNEL_LEAVES,
                "auth": DECLARED_WORKSET_AUTH_LEAVES,
            },
            what="workset",
        )

    if head == "box":
        return _scope_reason(
            "box", rest,
            leaves=DECLARED_BOX_LEAVES,
            sub_tables={"auth": DECLARED_BOX_AUTH_LEAVES},
            what="box",
        )

    if head == "agent":
        # The agent tier is DISCRIMINATED — ``agent.<agent>`` or
        # ``agent.default`` (spec §2d, §0). A bare ``agent.<key>`` is
        # NOT a key, and the code must REFUSE it rather than quietly accept it.
        if not rest:
            return "'agent' is a namespace, not a key (spec §2d)"
        name = rest[0]
        if not is_valid_agent_segment(name, valid_agents):
            return _bad_agent_reason(name, valid_agents)
        return _agent_tail_reason(f"agent.{name}", rest[1:], leaves)

    return (
        f"'{head}' is not a declared namespace (declared: config, system, "
        f"agent, workset, box, meta, pref) — the keyspace is CLOSED (spec §0)"
    )
